/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx}"],
  /* Improvement 12: Container breakpoints */
  theme: {
    screens: {
      'xs': '475px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      '3xl': '1920px',
    },
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        sm: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        '2xl': '4rem',
      },
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        gs: {
          bg: 'var(--gs-bg, #080808)',
          card: 'var(--gs-card, #0f0f0f)',
          surface: 'var(--gs-surface, #0d0d0d)',
          sidebar: 'var(--gs-sidebar, #0a0a0a)',
          border: 'var(--gs-border, #1e1e1e)',
          'border-subtle': 'var(--gs-border-subtle, #161616)',
          'border-hover': 'var(--gs-border-hover, #2a2a2a)',
          accent: 'var(--gs-accent, #0ea5e9)',
          indigo: 'var(--gs-indigo, #6366f1)',
          text: 'var(--gs-text, #f5f5f5)',
          muted: 'var(--gs-muted, #888888)',
          dim: 'var(--gs-dim, #555555)',
          faint: 'var(--gs-faint, #444444)',
          subtle: 'var(--gs-subtle, #333333)',
          /* Improvement 11: Extended color palette */
          success: '#10b981',
          warning: '#f59e0b',
          danger: '#ef4444',
          info: '#06b6d4',
          'accent-light': '#38bdf8',
          'accent-dark': '#0369a1',
          'indigo-light': '#818cf8',
          'indigo-dark': '#4338ca',
          /* Improvement 9: Light theme color tokens */
          'light-bg': '#f8f8f8',
          'light-card': '#ffffff',
          'light-surface': '#ffffff',
          'light-sidebar': '#f0f0f0',
          'light-border': '#e0e0e0',
          'light-text': '#111111',
          'light-muted': '#555555',
          'light-highlight': '#fffbeb',
          'light-input-bg': '#ffffff',
          'light-input-border': '#d1d5db',
          'light-badge-bg': '#f3f4f6',
          'light-skeleton': '#e5e7eb',
        },
        /* Improvement 12: Chart colors mapped to Tailwind classes */
        chart: {
          1: 'var(--gs-chart-1, #0ea5e9)',
          2: 'var(--gs-chart-2, #6366f1)',
          3: 'var(--gs-chart-3, #10b981)',
          4: 'var(--gs-chart-4, #f59e0b)',
          5: 'var(--gs-chart-5, #ef4444)',
          6: 'var(--gs-chart-6, #8b5cf6)',
          7: 'var(--gs-chart-7, #ec4899)',
          8: 'var(--gs-chart-8, #14b8a6)',
        },
      },
      fontFamily: {
        sans: ["'DM Sans'", '-apple-system', 'sans-serif'],
        mono: ["'DM Mono'", 'monospace'],
      },
      /* Improvement 11: Typography plugin-like utilities */
      fontSize: {
        'xxs': ['0.625rem', { lineHeight: '0.875rem' }],
        'label': ['0.6875rem', { lineHeight: '1rem', fontWeight: '600', letterSpacing: '0.08em' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.25rem' }],
        'body': ['0.875rem', { lineHeight: '1.375rem' }],
        'body-lg': ['1rem', { lineHeight: '1.5rem' }],
        'heading-sm': ['1.125rem', { lineHeight: '1.5rem', fontWeight: '700' }],
        'heading': ['1.5rem', { lineHeight: '2rem', fontWeight: '700' }],
        'heading-lg': ['2rem', { lineHeight: '2.5rem', fontWeight: '800' }],
        'display': ['2.5rem', { lineHeight: '3rem', fontWeight: '800' }],
        'display-lg': ['3.5rem', { lineHeight: '4rem', fontWeight: '800' }],
      },
      letterSpacing: {
        'label': '0.08em',
        'tight': '-0.01em',
        'display': '-0.025em',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '100': '25rem',
        '120': '30rem',
        /* Improvement 10: Custom spacing for common patterns */
        'sidebar': '240px',
        'sidebar-sm': '64px',
        'header': '64px',
        'mobile-bar': '72px',
        'card-gap': '1.25rem',
        'section-gap': '2.5rem',
        'page-x': '1.5rem',
        'page-x-lg': '3rem',
        'modal-pad': '1.5rem',
        'input-height': '2.75rem',
        'btn-height': '2.5rem',
        'avatar-sm': '2rem',
        'avatar-md': '2.5rem',
        'avatar-lg': '3.5rem',
      },
      /* Improvement 13: Aspect ratio extensions */
      aspectRatio: {
        'album': '1 / 1',
        'cover-art': '1 / 1',
        'banner': '3 / 1',
        'card': '4 / 3',
        'wide': '16 / 9',
        'ultrawide': '21 / 9',
      },
      /* Improvement 14: Backdrop blur/brightness utilities */
      backdropBlur: {
        xs: '2px',
        '2xl': '40px',
        '3xl': '64px',
      },
      backdropBrightness: {
        15: '.15',
        25: '.25',
        175: '1.75',
      },
      /* Improvement 15: Grid template columns/rows for layout areas */
      gridTemplateColumns: {
        'sidebar': '240px 1fr',
        'sidebar-collapsed': '64px 1fr',
        'catalog': 'repeat(auto-fill, minmax(180px, 1fr))',
        'catalog-lg': 'repeat(auto-fill, minmax(220px, 1fr))',
      },
      gridTemplateRows: {
        'layout': 'auto 1fr auto',
        'card': 'auto 1fr auto',
      },
      /* Improvement 21: Card flip transform utilities */
      rotate: {
        'y-0': '0deg',
        'y-180': '180deg',
        'x-0': '0deg',
        'x-180': '180deg',
      },
      transformOrigin: {
        'center-center': 'center center',
      },
      perspective: {
        'none': 'none',
        '500': '500px',
        '800': '800px',
        '1000': '1000px',
        '1500': '1500px',
        '2000': '2000px',
      },
      /* Improvement 22: Drawer width utilities */
      width: {
        'drawer-sm': '280px',
        'drawer': '320px',
        'drawer-md': '400px',
        'drawer-lg': '480px',
        'drawer-xl': '560px',
      },
      maxWidth: {
        'drawer-sm': '280px',
        'drawer': '320px',
        'drawer-md': '400px',
        'drawer-lg': '480px',
        'drawer-xl': '560px',
      },
      /* Improvement 23: Bottom sheet height utilities */
      height: {
        'sheet-sm': '30vh',
        'sheet': '50vh',
        'sheet-md': '65vh',
        'sheet-lg': '80vh',
        'sheet-full': '95vh',
      },
      maxHeight: {
        'sheet-sm': '30vh',
        'sheet': '50vh',
        'sheet-md': '65vh',
        'sheet-lg': '80vh',
        'sheet-full': '95vh',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-up': 'slideUp 0.25s ease-out',
        'heart-pop': 'heartPop 0.35s ease-out',
        'skeleton': 'skeleton 1.5s ease-in-out infinite',
        'page-in': 'pageIn 0.3s ease-out',
        'double-tap-heart': 'doubleTapHeart 0.8s ease-out forwards',
        'modal-in': 'modalIn 0.2s ease-out',
        'modal-out': 'modalOut 0.15s ease-in forwards',
        'overlay-in': 'overlayIn 0.2s ease-out',
        'overlay-out': 'overlayOut 0.15s ease-in forwards',
        'toast-in': 'toastIn 0.3s ease-out',
        'toast-out': 'toastOut 0.2s ease-in forwards',
        'shimmer': 'shimmer 1.8s ease-in-out infinite',
        'spin-slow': 'spinSlow 8s linear infinite',
        'mode-switch': 'modeSwitch 0.35s ease-out',
        'bounce-in': 'bounceIn 0.5s cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        'fade-in-up': 'fadeInUp 0.4s ease-out',
        'rotate-in': 'rotateIn 0.4s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        modalIn: {
          '0%': { opacity: '0', transform: 'scale(0.95) translateY(8px)' },
          '100%': { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        modalOut: {
          '0%': { opacity: '1', transform: 'scale(1) translateY(0)' },
          '100%': { opacity: '0', transform: 'scale(0.95) translateY(8px)' },
        },
        overlayIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        overlayOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        toastIn: {
          '0%': { opacity: '0', transform: 'translateX(-50%) translateY(16px) scale(0.95)' },
          '100%': { opacity: '1', transform: 'translateX(-50%) translateY(0) scale(1)' },
        },
        toastOut: {
          '0%': { opacity: '1', transform: 'translateX(-50%) translateY(0) scale(1)' },
          '100%': { opacity: '0', transform: 'translateX(-50%) translateY(16px) scale(0.95)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        heartPop: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.35)' },
          '100%': { transform: 'scale(1)' },
        },
        skeleton: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        pageIn: {
          '0%': { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        spinSlow: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        modeSwitch: {
          '0%': { opacity: '0', transform: 'translateY(8px) scale(0.98)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        bounceIn: {
          '0%': { opacity: '0', transform: 'scale(0.3)' },
          '50%': { opacity: '1', transform: 'scale(1.05)' },
          '70%': { transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        rotateIn: {
          '0%': { opacity: '0', transform: 'rotate(-10deg) scale(0.9)' },
          '100%': { opacity: '1', transform: 'rotate(0deg) scale(1)' },
        },
        doubleTapHeart: {
          '0%': { opacity: '0', transform: 'translate(-50%, -50%) scale(0)' },
          '15%': { opacity: '1', transform: 'translate(-50%, -50%) scale(1.2)' },
          '30%': { transform: 'translate(-50%, -50%) scale(1)' },
          '80%': { opacity: '1', transform: 'translate(-50%, -50%) scale(1)' },
          '100%': { opacity: '0', transform: 'translate(-50%, -50%) scale(0.8)' },
        },
      },
    },
  },
  plugins: [],
};
