// Seed listening history — simulates Vinyl Buddy sessions for demo purposes.
// When the Vinyl Buddy server is running, real sessions are merged in.
// Shape matches the server's /api/vinyl-buddy/history/:user response.
// Includes varied durations, times of day, and genre coverage for streak/achievement support.

const now = Date.now();
const hr = 3600000;
const day = 86400000;

const INITIAL_LISTENING = [
  // ── creator (current user) — 25 sessions across 10+ days for streak support ─
  { id: "ls-001", username: "creator", deviceId: "AABB11223344", track: { title: "Wish You Were Here", artist: "Pink Floyd", album: "Wish You Were Here", year: 1975 }, genre: "Rock", duration: 325, score: 97, timestamp: new Date(now - 0.5 * hr).toISOString(), timestampMs: now - 0.5 * hr },
  { id: "ls-002", username: "creator", deviceId: "AABB11223344", track: { title: "So What", artist: "Miles Davis", album: "Kind of Blue", year: 1959 }, genre: "Jazz", duration: 561, score: 94, timestamp: new Date(now - 2 * hr).toISOString(), timestampMs: now - 2 * hr },
  { id: "ls-003", username: "creator", deviceId: "AABB11223344", track: { title: "Paranoid Android", artist: "Radiohead", album: "OK Computer", year: 1997 }, genre: "Alternative", duration: 386, score: 91, timestamp: new Date(now - 5 * hr).toISOString(), timestampMs: now - 5 * hr },
  { id: "ls-004", username: "creator", deviceId: "AABB11223344", track: { title: "Nights", artist: "Frank Ocean", album: "Blonde", year: 2016 }, genre: "R&B", duration: 306, score: 89, timestamp: new Date(now - 8 * hr).toISOString(), timestampMs: now - 8 * hr },
  { id: "ls-005", username: "creator", deviceId: "AABB11223344", track: { title: "Flim", artist: "Aphex Twin", album: "Come to Daddy", year: 1997 }, genre: "Electronic", duration: 175, score: 93, timestamp: new Date(now - 1 * day).toISOString(), timestampMs: now - 1 * day },
  { id: "ls-006", username: "creator", deviceId: "AABB11223344", track: { title: "Everything In Its Right Place", artist: "Radiohead", album: "Kid A", year: 2000 }, genre: "Alternative", duration: 264, score: 96, timestamp: new Date(now - 1.2 * day).toISOString(), timestampMs: now - 1.2 * day },
  { id: "ls-007", username: "creator", deviceId: "AABB11223344", track: { title: "Maiden Voyage", artist: "Herbie Hancock", album: "Maiden Voyage", year: 1965 }, genre: "Jazz", duration: 483, score: 88, timestamp: new Date(now - 1.5 * day).toISOString(), timestampMs: now - 1.5 * day },
  { id: "ls-008", username: "creator", deviceId: "AABB11223344", track: { title: "Redbone", artist: "Childish Gambino", album: "Awaken, My Love!", year: 2016 }, genre: "Funk", duration: 327, score: 95, timestamp: new Date(now - 2 * day).toISOString(), timestampMs: now - 2 * day },
  { id: "ls-009", username: "creator", deviceId: "AABB11223344", track: { title: "Goodbye Pork Pie Hat", artist: "Charles Mingus", album: "Mingus Ah Um", year: 1959 }, genre: "Jazz", duration: 346, score: 92, timestamp: new Date(now - 2.5 * day).toISOString(), timestampMs: now - 2.5 * day },
  { id: "ls-010", username: "creator", deviceId: "AABB11223344", track: { title: "Chameleon", artist: "Herbie Hancock", album: "Head Hunters", year: 1973 }, genre: "Jazz", duration: 930, score: 96, timestamp: new Date(now - 3 * day).toISOString(), timestampMs: now - 3 * day },
  { id: "ls-011", username: "creator", deviceId: "AABB11223344", track: { title: "Teardrop", artist: "Massive Attack", album: "Mezzanine", year: 1998 }, genre: "Electronic", duration: 328, score: 90, timestamp: new Date(now - 3.5 * day).toISOString(), timestampMs: now - 3.5 * day },
  { id: "ls-012", username: "creator", deviceId: "AABB11223344", track: { title: "Only Shallow", artist: "My Bloody Valentine", album: "Loveless", year: 1991 }, genre: "Alternative", duration: 248, score: 94, timestamp: new Date(now - 4 * day).toISOString(), timestampMs: now - 4 * day },
  { id: "ls-013", username: "creator", deviceId: "AABB11223344", track: { title: "N.Y. State of Mind", artist: "Nas", album: "Illmatic", year: 1994 }, genre: "Hip-Hop", duration: 290, score: 97, timestamp: new Date(now - 5 * day).toISOString(), timestampMs: now - 5 * day },
  // creator marathon session — 4+ hours in one evening (late night)
  { id: "ls-014", username: "creator", deviceId: "AABB11223344", track: { title: "Echoes", artist: "Pink Floyd", album: "Meddle", year: 1971 }, genre: "Rock", duration: 1403, score: 98, timestamp: new Date(now - 5.5 * day).toISOString(), timestampMs: now - 5.5 * day },
  { id: "ls-015", username: "creator", deviceId: "AABB11223344", track: { title: "A Love Supreme, Pt. 1", artist: "John Coltrane", album: "A Love Supreme", year: 1965 }, genre: "Jazz", duration: 462, score: 99, timestamp: new Date(now - 6 * day).toISOString(), timestampMs: now - 6 * day },
  { id: "ls-016", username: "creator", deviceId: "AABB11223344", track: { title: "Alright", artist: "Kendrick Lamar", album: "To Pimp a Butterfly", year: 2015 }, genre: "Hip-Hop", duration: 219, score: 95, timestamp: new Date(now - 6.5 * day).toISOString(), timestampMs: now - 6.5 * day },
  { id: "ls-017", username: "creator", deviceId: "AABB11223344", track: { title: "Stir It Up", artist: "Bob Marley & The Wailers", album: "Catch a Fire", year: 1973 }, genre: "Reggae", duration: 329, score: 91, timestamp: new Date(now - 7 * day).toISOString(), timestampMs: now - 7 * day },
  // creator late-night listens (after midnight)
  { id: "ls-018", username: "creator", deviceId: "AABB11223344", track: { title: "Self Control", artist: "Frank Ocean", album: "Blonde", year: 2016 }, genre: "R&B", duration: 249, score: 96, timestamp: new Date(now - 7.9 * day).toISOString(), timestampMs: now - 7.9 * day },
  { id: "ls-019", username: "creator", deviceId: "AABB11223344", track: { title: "Svefn-g-englar", artist: "Sigur Ros", album: "Agaetis byrjun", year: 1999 }, genre: "Alternative", duration: 610, score: 93, timestamp: new Date(now - 8 * day).toISOString(), timestampMs: now - 8 * day },
  { id: "ls-020", username: "creator", deviceId: "AABB11223344", track: { title: "Maggot Brain", artist: "Funkadelic", album: "Maggot Brain", year: 1971 }, genre: "Funk", duration: 602, score: 98, timestamp: new Date(now - 8.5 * day).toISOString(), timestampMs: now - 8.5 * day },
  { id: "ls-021", username: "creator", deviceId: "AABB11223344", track: { title: "Disorder", artist: "Joy Division", album: "Unknown Pleasures", year: 1979 }, genre: "Alternative", duration: 211, score: 94, timestamp: new Date(now - 9 * day).toISOString(), timestampMs: now - 9 * day },
  { id: "ls-022", username: "creator", deviceId: "AABB11223344", track: { title: "Watermelon Man", artist: "Herbie Hancock", album: "Head Hunters", year: 1973 }, genre: "Jazz", duration: 382, score: 93, timestamp: new Date(now - 9.5 * day).toISOString(), timestampMs: now - 9.5 * day },
  // creator short play — preview spin
  { id: "ls-023", username: "creator", deviceId: "AABB11223344", track: { title: "Idioteque", artist: "Radiohead", album: "Kid A", year: 2000 }, genre: "Alternative", duration: 65, score: 88, timestamp: new Date(now - 10 * day).toISOString(), timestampMs: now - 10 * day },
  { id: "ls-024", username: "creator", deviceId: "AABB11223344", track: { title: "Superstition", artist: "Stevie Wonder", album: "Talking Book", year: 1972 }, genre: "Soul", duration: 245, score: 97, timestamp: new Date(now - 10.5 * day).toISOString(), timestampMs: now - 10.5 * day },
  { id: "ls-025", username: "creator", deviceId: "AABB11223344", track: { title: "Gymnopedies No. 1", artist: "Erik Satie", album: "Gymnopedies", year: 1888 }, genre: "Classical", duration: 198, score: 90, timestamp: new Date(now - 11 * day).toISOString(), timestampMs: now - 11 * day },

  // ── mara.vinyl — 7 sessions ───────────────────────────────────────────────
  { id: "ls-101", username: "mara.vinyl", deviceId: "CC1122334455", track: { title: "Svefn-g-englar", artist: "Sigur Ros", album: "Agaetis byrjun", year: 1999 }, genre: "Alternative", duration: 610, score: 90, timestamp: new Date(now - 1 * hr).toISOString(), timestampMs: now - 1 * hr },
  { id: "ls-102", username: "mara.vinyl", deviceId: "CC1122334455", track: { title: "Nude", artist: "Radiohead", album: "In Rainbows", year: 2007 }, genre: "Alternative", duration: 256, score: 92, timestamp: new Date(now - 6 * hr).toISOString(), timestampMs: now - 6 * hr },
  { id: "ls-103", username: "mara.vinyl", deviceId: "CC1122334455", track: { title: "Breathe", artist: "Pink Floyd", album: "The Dark Side of the Moon", year: 1973 }, genre: "Rock", duration: 169, score: 96, timestamp: new Date(now - 1 * day).toISOString(), timestampMs: now - 1 * day },
  { id: "ls-104", username: "mara.vinyl", deviceId: "CC1122334455", track: { title: "Naima", artist: "John Coltrane", album: "Giant Steps", year: 1960 }, genre: "Jazz", duration: 278, score: 95, timestamp: new Date(now - 2 * day).toISOString(), timestampMs: now - 2 * day },
  { id: "ls-105", username: "mara.vinyl", deviceId: "CC1122334455", track: { title: "Blue in Green", artist: "Miles Davis", album: "Kind of Blue", year: 1959 }, genre: "Jazz", duration: 327, score: 98, timestamp: new Date(now - 3.5 * day).toISOString(), timestampMs: now - 3.5 * day },
  { id: "ls-106", username: "mara.vinyl", deviceId: "CC1122334455", track: { title: "Goodbye Pork Pie Hat", artist: "Charles Mingus", album: "Mingus Ah Um", year: 1959 }, genre: "Jazz", duration: 346, score: 94, timestamp: new Date(now - 5 * day).toISOString(), timestampMs: now - 5 * day },
  { id: "ls-107", username: "mara.vinyl", deviceId: "CC1122334455", track: { title: "In a Sentimental Mood", artist: "Duke Ellington & John Coltrane", album: "Duke Ellington & John Coltrane", year: 1963 }, genre: "Jazz", duration: 280, score: 97, timestamp: new Date(now - 7 * day).toISOString(), timestampMs: now - 7 * day },

  // ── thomas.wax — 7 sessions ───────────────────────────────────────────────
  { id: "ls-201", username: "thomas.wax", deviceId: "DD2233445566", track: { title: "A Love Supreme, Pt. 1", artist: "John Coltrane", album: "A Love Supreme", year: 1965 }, genre: "Jazz", duration: 462, score: 98, timestamp: new Date(now - 3 * hr).toISOString(), timestampMs: now - 3 * hr },
  { id: "ls-202", username: "thomas.wax", deviceId: "DD2233445566", track: { title: "Blue in Green", artist: "Miles Davis", album: "Kind of Blue", year: 1959 }, genre: "Jazz", duration: 327, score: 95, timestamp: new Date(now - 10 * hr).toISOString(), timestampMs: now - 10 * hr },
  { id: "ls-203", username: "thomas.wax", deviceId: "DD2233445566", track: { title: "My Favorite Things", artist: "John Coltrane", album: "My Favorite Things", year: 1961 }, genre: "Jazz", duration: 815, score: 91, timestamp: new Date(now - 2 * day).toISOString(), timestampMs: now - 2 * day },
  { id: "ls-204", username: "thomas.wax", deviceId: "DD2233445566", track: { title: "Whole Lotta Love", artist: "Led Zeppelin", album: "Led Zeppelin II", year: 1969 }, genre: "Rock", duration: 334, score: 96, timestamp: new Date(now - 3 * day).toISOString(), timestampMs: now - 3 * day },
  { id: "ls-205", username: "thomas.wax", deviceId: "DD2233445566", track: { title: "Baba O'Riley", artist: "The Who", album: "Who's Next", year: 1971 }, genre: "Rock", duration: 300, score: 93, timestamp: new Date(now - 4.5 * day).toISOString(), timestampMs: now - 4.5 * day },
  { id: "ls-206", username: "thomas.wax", deviceId: "DD2233445566", track: { title: "Stairway to Heaven", artist: "Led Zeppelin", album: "Led Zeppelin IV", year: 1971 }, genre: "Rock", duration: 482, score: 97, timestamp: new Date(now - 6 * day).toISOString(), timestampMs: now - 6 * day },
  { id: "ls-207", username: "thomas.wax", deviceId: "DD2233445566", track: { title: "Bohemian Rhapsody", artist: "Queen", album: "A Night at the Opera", year: 1975 }, genre: "Rock", duration: 355, score: 98, timestamp: new Date(now - 8 * day).toISOString(), timestampMs: now - 8 * day },

  // ── juniper.sounds — 7 sessions ───────────────────────────────────────────
  { id: "ls-301", username: "juniper.sounds", deviceId: "EE3344556677", track: { title: "Hyperballad", artist: "Bjork", album: "Post", year: 1995 }, genre: "Electronic", duration: 312, score: 93, timestamp: new Date(now - 4 * hr).toISOString(), timestampMs: now - 4 * hr },
  { id: "ls-302", username: "juniper.sounds", deviceId: "EE3344556677", track: { title: "Windowlicker", artist: "Aphex Twin", album: "Windowlicker", year: 1999 }, genre: "Electronic", duration: 363, score: 87, timestamp: new Date(now - 12 * hr).toISOString(), timestampMs: now - 12 * hr },
  { id: "ls-303", username: "juniper.sounds", deviceId: "EE3344556677", track: { title: "Archangel", artist: "Burial", album: "Untrue", year: 2007 }, genre: "Electronic", duration: 235, score: 95, timestamp: new Date(now - 1.5 * day).toISOString(), timestampMs: now - 1.5 * day },
  { id: "ls-304", username: "juniper.sounds", deviceId: "EE3344556677", track: { title: "Roygbiv", artist: "Boards of Canada", album: "Music Has the Right to Children", year: 1998 }, genre: "Electronic", duration: 146, score: 91, timestamp: new Date(now - 2.5 * day).toISOString(), timestampMs: now - 2.5 * day },
  { id: "ls-305", username: "juniper.sounds", deviceId: "EE3344556677", track: { title: "Da Funk", artist: "Daft Punk", album: "Homework", year: 1997 }, genre: "Electronic", duration: 329, score: 88, timestamp: new Date(now - 4 * day).toISOString(), timestampMs: now - 4 * day },
  { id: "ls-306", username: "juniper.sounds", deviceId: "EE3344556677", track: { title: "Xtal", artist: "Aphex Twin", album: "Selected Ambient Works 85-92", year: 1992 }, genre: "Electronic", duration: 281, score: 96, timestamp: new Date(now - 6 * day).toISOString(), timestampMs: now - 6 * day },
  { id: "ls-307", username: "juniper.sounds", deviceId: "EE3344556677", track: { title: "Untitled", artist: "Burial", album: "Untrue", year: 2007 }, genre: "Electronic", duration: 304, score: 92, timestamp: new Date(now - 8 * day).toISOString(), timestampMs: now - 8 * day },

  // ── nadia.rpm — 6 sessions ────────────────────────────────────────────────
  { id: "ls-401", username: "nadia.rpm", deviceId: "FF4455667788", track: { title: "Alright", artist: "Kendrick Lamar", album: "To Pimp a Butterfly", year: 2015 }, genre: "Hip-Hop", duration: 219, score: 94, timestamp: new Date(now - 2 * hr).toISOString(), timestampMs: now - 2 * hr },
  { id: "ls-402", username: "nadia.rpm", deviceId: "FF4455667788", track: { title: "Electric Feel", artist: "MGMT", album: "Oracular Spectacular", year: 2007 }, genre: "Alternative", duration: 229, score: 90, timestamp: new Date(now - 18 * hr).toISOString(), timestampMs: now - 18 * hr },
  { id: "ls-403", username: "nadia.rpm", deviceId: "FF4455667788", track: { title: "C.R.E.A.M.", artist: "Wu-Tang Clan", album: "Enter the Wu-Tang (36 Chambers)", year: 1993 }, genre: "Hip-Hop", duration: 244, score: 96, timestamp: new Date(now - 1.5 * day).toISOString(), timestampMs: now - 1.5 * day },
  { id: "ls-404", username: "nadia.rpm", deviceId: "FF4455667788", track: { title: "Juicy", artist: "The Notorious B.I.G.", album: "Ready to Die", year: 1994 }, genre: "Hip-Hop", duration: 320, score: 97, timestamp: new Date(now - 3 * day).toISOString(), timestampMs: now - 3 * day },
  { id: "ls-405", username: "nadia.rpm", deviceId: "FF4455667788", track: { title: "Shook Ones Pt. II", artist: "Mobb Deep", album: "The Infamous", year: 1995 }, genre: "Hip-Hop", duration: 286, score: 95, timestamp: new Date(now - 5 * day).toISOString(), timestampMs: now - 5 * day },
  { id: "ls-406", username: "nadia.rpm", deviceId: "FF4455667788", track: { title: "Protect Ya Neck", artist: "Wu-Tang Clan", album: "Enter the Wu-Tang (36 Chambers)", year: 1993 }, genre: "Hip-Hop", duration: 293, score: 93, timestamp: new Date(now - 7 * day).toISOString(), timestampMs: now - 7 * day },

  // ── felix.rpm — 5 sessions ────────────────────────────────────────────────
  { id: "ls-501", username: "felix.rpm", deviceId: "AA5566778899", track: { title: "Bohemian Rhapsody", artist: "Queen", album: "A Night at the Opera", year: 1975 }, genre: "Rock", duration: 355, score: 99, timestamp: new Date(now - 7 * hr).toISOString(), timestampMs: now - 7 * hr },
  { id: "ls-502", username: "felix.rpm", deviceId: "AA5566778899", track: { title: "Stairway to Heaven", artist: "Led Zeppelin", album: "Led Zeppelin IV", year: 1971 }, genre: "Rock", duration: 482, score: 97, timestamp: new Date(now - 1.5 * day).toISOString(), timestampMs: now - 1.5 * day },
  { id: "ls-503", username: "felix.rpm", deviceId: "AA5566778899", track: { title: "Watermelon Man", artist: "Herbie Hancock", album: "Head Hunters", year: 1973 }, genre: "Jazz", duration: 382, score: 93, timestamp: new Date(now - 3 * day).toISOString(), timestampMs: now - 3 * day },
  { id: "ls-504", username: "felix.rpm", deviceId: "AA5566778899", track: { title: "Oye Como Va", artist: "Tito Puente", album: "Dance Mania", year: 1958 }, genre: "World", duration: 264, score: 91, timestamp: new Date(now - 5 * day).toISOString(), timestampMs: now - 5 * day },
  { id: "ls-505", username: "felix.rpm", deviceId: "AA5566778899", track: { title: "Desafinado", artist: "Stan Getz & Joao Gilberto", album: "Getz/Gilberto", year: 1964 }, genre: "Jazz", duration: 245, score: 94, timestamp: new Date(now - 7 * day).toISOString(), timestampMs: now - 7 * day },

  // ── yuki.vinyl — 6 sessions ───────────────────────────────────────────────
  { id: "ls-601", username: "yuki.vinyl", deviceId: "BB6677889900", track: { title: "Plastic Love", artist: "Mariya Takeuchi", album: "Variety", year: 1984 }, genre: "Pop", duration: 298, score: 92, timestamp: new Date(now - 3 * hr).toISOString(), timestampMs: now - 3 * hr },
  { id: "ls-602", username: "yuki.vinyl", deviceId: "BB6677889900", track: { title: "Stay With Me", artist: "Miki Matsubara", album: "Pocket Park", year: 1980 }, genre: "Pop", duration: 235, score: 86, timestamp: new Date(now - 1 * day).toISOString(), timestampMs: now - 1 * day },
  { id: "ls-603", username: "yuki.vinyl", deviceId: "BB6677889900", track: { title: "Scenery", artist: "Ryo Fukui", album: "Scenery", year: 1976 }, genre: "Jazz", duration: 415, score: 94, timestamp: new Date(now - 2 * day).toISOString(), timestampMs: now - 2 * day },
  { id: "ls-604", username: "yuki.vinyl", deviceId: "BB6677889900", track: { title: "My Favorite Things", artist: "John Coltrane", album: "My Favorite Things", year: 1961 }, genre: "Jazz", duration: 815, score: 97, timestamp: new Date(now - 4 * day).toISOString(), timestampMs: now - 4 * day },
  { id: "ls-605", username: "yuki.vinyl", deviceId: "BB6677889900", track: { title: "Behind the Mask", artist: "Yellow Magic Orchestra", album: "Solid State Survivor", year: 1979 }, genre: "Electronic", duration: 266, score: 90, timestamp: new Date(now - 6 * day).toISOString(), timestampMs: now - 6 * day },
  { id: "ls-606", username: "yuki.vinyl", deviceId: "BB6677889900", track: { title: "Ride on Time", artist: "Tatsuro Yamashita", album: "Ride on Time", year: 1980 }, genre: "Pop", duration: 308, score: 93, timestamp: new Date(now - 8 * day).toISOString(), timestampMs: now - 8 * day },

  // ── cleo.spins — 5 sessions ───────────────────────────────────────────────
  { id: "ls-701", username: "cleo.spins", deviceId: "CC7788990011", track: { title: "When You Sleep", artist: "My Bloody Valentine", album: "Loveless", year: 1991 }, genre: "Alternative", duration: 252, score: 96, timestamp: new Date(now - 1 * hr).toISOString(), timestampMs: now - 1 * hr },
  { id: "ls-702", username: "cleo.spins", deviceId: "CC7788990011", track: { title: "Alison", artist: "Slowdive", album: "Souvlaki", year: 1993 }, genre: "Alternative", duration: 305, score: 93, timestamp: new Date(now - 8 * hr).toISOString(), timestampMs: now - 8 * hr },
  { id: "ls-703", username: "cleo.spins", deviceId: "CC7788990011", track: { title: "Mayonaise", artist: "The Smashing Pumpkins", album: "Siamese Dream", year: 1993 }, genre: "Alternative", duration: 348, score: 90, timestamp: new Date(now - 2 * day).toISOString(), timestampMs: now - 2 * day },
  { id: "ls-704", username: "cleo.spins", deviceId: "CC7788990011", track: { title: "Gold Soundz", artist: "Pavement", album: "Crooked Rain, Crooked Rain", year: 1994 }, genre: "Alternative", duration: 147, score: 91, timestamp: new Date(now - 4 * day).toISOString(), timestampMs: now - 4 * day },
  { id: "ls-705", username: "cleo.spins", deviceId: "CC7788990011", track: { title: "Cut Your Hair", artist: "Pavement", album: "Crooked Rain, Crooked Rain", year: 1994 }, genre: "Alternative", duration: 181, score: 88, timestamp: new Date(now - 6 * day).toISOString(), timestampMs: now - 6 * day },

  // ── otto.wax — 5 sessions ─────────────────────────────────────────────────
  { id: "ls-801", username: "otto.wax", deviceId: "DD8899001122", track: { title: "Disorder", artist: "Joy Division", album: "Unknown Pleasures", year: 1979 }, genre: "Alternative", duration: 211, score: 95, timestamp: new Date(now - 2 * hr).toISOString(), timestampMs: now - 2 * hr },
  { id: "ls-802", username: "otto.wax", deviceId: "DD8899001122", track: { title: "Bela Lugosi's Dead", artist: "Bauhaus", album: "In the Flat Field", year: 1980 }, genre: "Alternative", duration: 564, score: 91, timestamp: new Date(now - 14 * hr).toISOString(), timestampMs: now - 14 * hr },
  { id: "ls-803", username: "otto.wax", deviceId: "DD8899001122", track: { title: "A Forest", artist: "The Cure", album: "Seventeen Seconds", year: 1980 }, genre: "Alternative", duration: 352, score: 88, timestamp: new Date(now - 2.5 * day).toISOString(), timestampMs: now - 2.5 * day },
  { id: "ls-804", username: "otto.wax", deviceId: "DD8899001122", track: { title: "She's Lost Control", artist: "Joy Division", album: "Unknown Pleasures", year: 1979 }, genre: "Alternative", duration: 225, score: 94, timestamp: new Date(now - 5 * day).toISOString(), timestampMs: now - 5 * day },
  { id: "ls-805", username: "otto.wax", deviceId: "DD8899001122", track: { title: "Transmission", artist: "Joy Division", album: "Substance", year: 1980 }, genre: "Alternative", duration: 229, score: 96, timestamp: new Date(now - 7 * day).toISOString(), timestampMs: now - 7 * day },

  // ── bjorn.grooves — 5 sessions ────────────────────────────────────────────
  { id: "ls-901", username: "bjorn.grooves", deviceId: "EE9900112233", track: { title: "Battery", artist: "Metallica", album: "Master of Puppets", year: 1986 }, genre: "Metal", duration: 313, score: 98, timestamp: new Date(now - 5 * hr).toISOString(), timestampMs: now - 5 * hr },
  { id: "ls-902", username: "bjorn.grooves", deviceId: "EE9900112233", track: { title: "War Pigs", artist: "Black Sabbath", album: "Paranoid", year: 1970 }, genre: "Metal", duration: 467, score: 95, timestamp: new Date(now - 1 * day).toISOString(), timestampMs: now - 1 * day },
  { id: "ls-903", username: "bjorn.grooves", deviceId: "EE9900112233", track: { title: "Raining Blood", artist: "Slayer", album: "Reign in Blood", year: 1986 }, genre: "Metal", duration: 252, score: 97, timestamp: new Date(now - 3.5 * day).toISOString(), timestampMs: now - 3.5 * day },
  { id: "ls-904", username: "bjorn.grooves", deviceId: "EE9900112233", track: { title: "Hallowed Be Thy Name", artist: "Iron Maiden", album: "The Number of the Beast", year: 1982 }, genre: "Metal", duration: 432, score: 96, timestamp: new Date(now - 6 * day).toISOString(), timestampMs: now - 6 * day },
  { id: "ls-905", username: "bjorn.grooves", deviceId: "EE9900112233", track: { title: "Ace of Spades", artist: "Motorhead", album: "Ace of Spades", year: 1980 }, genre: "Metal", duration: 169, score: 94, timestamp: new Date(now - 9 * day).toISOString(), timestampMs: now - 9 * day },

  // ── lena.records — 5 sessions ─────────────────────────────────────────────
  { id: "ls-1001", username: "lena.records", deviceId: "FF0011223344", track: { title: "Respect", artist: "Aretha Franklin", album: "I Never Loved a Man the Way I Love You", year: 1967 }, genre: "Soul", duration: 147, score: 99, timestamp: new Date(now - 4 * hr).toISOString(), timestampMs: now - 4 * hr },
  { id: "ls-1002", username: "lena.records", deviceId: "FF0011223344", track: { title: "A Change Is Gonna Come", artist: "Sam Cooke", album: "Ain't That Good News", year: 1964 }, genre: "Soul", duration: 195, score: 96, timestamp: new Date(now - 1.5 * day).toISOString(), timestampMs: now - 1.5 * day },
  { id: "ls-1003", username: "lena.records", deviceId: "FF0011223344", track: { title: "Try a Little Tenderness", artist: "Otis Redding", album: "Complete & Unbelievable", year: 1966 }, genre: "Soul", duration: 228, score: 94, timestamp: new Date(now - 4 * day).toISOString(), timestampMs: now - 4 * day },
  { id: "ls-1004", username: "lena.records", deviceId: "FF0011223344", track: { title: "I Heard It Through the Grapevine", artist: "Marvin Gaye", album: "In the Groove", year: 1968 }, genre: "Soul", duration: 195, score: 95, timestamp: new Date(now - 6 * day).toISOString(), timestampMs: now - 6 * day },
  { id: "ls-1005", username: "lena.records", deviceId: "FF0011223344", track: { title: "Ain't No Mountain High Enough", artist: "Marvin Gaye & Tammi Terrell", album: "United", year: 1967 }, genre: "Soul", duration: 155, score: 93, timestamp: new Date(now - 8 * day).toISOString(), timestampMs: now - 8 * day },

  // ── max.plays — 4 sessions ────────────────────────────────────────────────
  { id: "ls-1101", username: "max.plays", deviceId: "AA1122334466", track: { title: "Flash Light", artist: "Parliament", album: "Funkentelechy vs. the Placebo Syndrome", year: 1977 }, genre: "Funk", duration: 360, score: 95, timestamp: new Date(now - 6 * hr).toISOString(), timestampMs: now - 6 * hr },
  { id: "ls-1102", username: "max.plays", deviceId: "AA1122334466", track: { title: "Maggot Brain", artist: "Funkadelic", album: "Maggot Brain", year: 1971 }, genre: "Funk", duration: 602, score: 98, timestamp: new Date(now - 2 * day).toISOString(), timestampMs: now - 2 * day },
  { id: "ls-1103", username: "max.plays", deviceId: "AA1122334466", track: { title: "Give Up the Funk", artist: "Parliament", album: "Mothership Connection", year: 1975 }, genre: "Funk", duration: 275, score: 96, timestamp: new Date(now - 5 * day).toISOString(), timestampMs: now - 5 * day },
  { id: "ls-1104", username: "max.plays", deviceId: "AA1122334466", track: { title: "Super Stupid", artist: "Funkadelic", album: "Maggot Brain", year: 1971 }, genre: "Funk", duration: 253, score: 92, timestamp: new Date(now - 8 * day).toISOString(), timestampMs: now - 8 * day },

  // ── soren.stacks — 4 sessions ─────────────────────────────────────────────
  { id: "ls-1201", username: "soren.stacks", deviceId: "BB2233445577", track: { title: "1/1", artist: "Brian Eno", album: "Music for Airports", year: 1978 }, genre: "Electronic", duration: 1023, score: 90, timestamp: new Date(now - 9 * hr).toISOString(), timestampMs: now - 9 * hr },
  { id: "ls-1202", username: "soren.stacks", deviceId: "BB2233445577", track: { title: "In a Sentimental Mood", artist: "Duke Ellington & John Coltrane", album: "Duke Ellington & John Coltrane", year: 1963 }, genre: "Jazz", duration: 280, score: 93, timestamp: new Date(now - 2 * day).toISOString(), timestampMs: now - 2 * day },
  { id: "ls-1203", username: "soren.stacks", deviceId: "BB2233445577", track: { title: "An Ending (Ascent)", artist: "Brian Eno", album: "Apollo: Atmospheres and Soundtracks", year: 1983 }, genre: "Electronic", duration: 261, score: 95, timestamp: new Date(now - 5 * day).toISOString(), timestampMs: now - 5 * day },
  { id: "ls-1204", username: "soren.stacks", deviceId: "BB2233445577", track: { title: "Dis", artist: "Jan Garbarek", album: "Dis", year: 1977 }, genre: "Jazz", duration: 445, score: 91, timestamp: new Date(now - 8 * day).toISOString(), timestampMs: now - 8 * day },

  // ── dax.wax — 4 sessions ──────────────────────────────────────────────────
  { id: "ls-1301", username: "dax.wax", deviceId: "CC3344556688", track: { title: "Superstition", artist: "Stevie Wonder", album: "Talking Book", year: 1972 }, genre: "Soul", duration: 245, score: 96, timestamp: new Date(now - 3 * hr).toISOString(), timestampMs: now - 3 * hr },
  { id: "ls-1302", username: "dax.wax", deviceId: "CC3344556688", track: { title: "Papa Was a Rollin' Stone", artist: "The Temptations", album: "All Directions", year: 1972 }, genre: "Soul", duration: 412, score: 89, timestamp: new Date(now - 1 * day).toISOString(), timestampMs: now - 1 * day },
  { id: "ls-1303", username: "dax.wax", deviceId: "CC3344556688", track: { title: "Family Affair", artist: "Sly & The Family Stone", album: "There's a Riot Goin' On", year: 1971 }, genre: "Funk", duration: 189, score: 94, timestamp: new Date(now - 4 * day).toISOString(), timestampMs: now - 4 * day },
  { id: "ls-1304", username: "dax.wax", deviceId: "CC3344556688", track: { title: "Thank You", artist: "Sly & The Family Stone", album: "Stand!", year: 1969 }, genre: "Funk", duration: 287, score: 92, timestamp: new Date(now - 7 * day).toISOString(), timestampMs: now - 7 * day },

  // ── beau.plays — 5 sessions ───────────────────────────────────────────────
  { id: "ls-1401", username: "beau.plays", deviceId: "DD4455667799", track: { title: "Around the World", artist: "Daft Punk", album: "Homework", year: 1997 }, genre: "Electronic", duration: 425, score: 94, timestamp: new Date(now - 5 * hr).toISOString(), timestampMs: now - 5 * hr },
  { id: "ls-1402", username: "beau.plays", deviceId: "DD4455667799", track: { title: "Giorgio by Moroder", artist: "Daft Punk", album: "Random Access Memories", year: 2013 }, genre: "Electronic", duration: 544, score: 97, timestamp: new Date(now - 1 * day).toISOString(), timestampMs: now - 1 * day },
  { id: "ls-1403", username: "beau.plays", deviceId: "DD4455667799", track: { title: "I Feel Love", artist: "Donna Summer", album: "I Remember Yesterday", year: 1977 }, genre: "Electronic", duration: 495, score: 92, timestamp: new Date(now - 3 * day).toISOString(), timestampMs: now - 3 * day },
  { id: "ls-1404", username: "beau.plays", deviceId: "DD4455667799", track: { title: "Blue Monday", artist: "New Order", album: "Power, Corruption & Lies", year: 1983 }, genre: "Electronic", duration: 437, score: 93, timestamp: new Date(now - 5 * day).toISOString(), timestampMs: now - 5 * day },
  { id: "ls-1405", username: "beau.plays", deviceId: "DD4455667799", track: { title: "Strings of Life", artist: "Derrick May", album: "Innovator", year: 1987 }, genre: "Electronic", duration: 389, score: 90, timestamp: new Date(now - 8 * day).toISOString(), timestampMs: now - 8 * day },

  // ── zara.grooves — 4 sessions ─────────────────────────────────────────────
  { id: "ls-1501", username: "zara.grooves", deviceId: "EE5566778800", track: { title: "Stir It Up", artist: "Bob Marley & The Wailers", album: "Catch a Fire", year: 1973 }, genre: "Reggae", duration: 329, score: 93, timestamp: new Date(now - 7 * hr).toISOString(), timestampMs: now - 7 * hr },
  { id: "ls-1502", username: "zara.grooves", deviceId: "EE5566778800", track: { title: "Chase the Devil", artist: "Max Romeo & The Upsetters", album: "War ina Babylon", year: 1976 }, genre: "Reggae", duration: 228, score: 90, timestamp: new Date(now - 2 * day).toISOString(), timestampMs: now - 2 * day },
  { id: "ls-1503", username: "zara.grooves", deviceId: "EE5566778800", track: { title: "54-46 That's My Number", artist: "Toots & The Maytals", album: "Funky Kingston", year: 1973 }, genre: "Reggae", duration: 185, score: 91, timestamp: new Date(now - 5 * day).toISOString(), timestampMs: now - 5 * day },
  { id: "ls-1504", username: "zara.grooves", deviceId: "EE5566778800", track: { title: "Rivers of Babylon", artist: "The Melodians", album: "Rivers of Babylon", year: 1970 }, genre: "Reggae", duration: 196, score: 88, timestamp: new Date(now - 8 * day).toISOString(), timestampMs: now - 8 * day },

  // ── iris.rpm — 4 sessions ─────────────────────────────────────────────────
  { id: "ls-1601", username: "iris.rpm", deviceId: "FF6677889911", track: { title: "Roundabout", artist: "Yes", album: "Fragile", year: 1971 }, genre: "Rock", duration: 523, score: 94, timestamp: new Date(now - 11 * hr).toISOString(), timestampMs: now - 11 * hr },
  { id: "ls-1602", username: "iris.rpm", deviceId: "FF6677889911", track: { title: "21st Century Schizoid Man", artist: "King Crimson", album: "In the Court of the Crimson King", year: 1969 }, genre: "Rock", duration: 442, score: 92, timestamp: new Date(now - 2 * day).toISOString(), timestampMs: now - 2 * day },
  { id: "ls-1603", username: "iris.rpm", deviceId: "FF6677889911", track: { title: "Close to the Edge", artist: "Yes", album: "Close to the Edge", year: 1972 }, genre: "Rock", duration: 1098, score: 97, timestamp: new Date(now - 5 * day).toISOString(), timestampMs: now - 5 * day },
  { id: "ls-1604", username: "iris.rpm", deviceId: "FF6677889911", track: { title: "Supper's Ready", artist: "Genesis", album: "Foxtrot", year: 1972 }, genre: "Rock", duration: 1380, score: 95, timestamp: new Date(now - 9 * day).toISOString(), timestampMs: now - 9 * day },

  // ── riku.records — 4 sessions ─────────────────────────────────────────────
  { id: "ls-1701", username: "riku.records", deviceId: "AA7788990022", track: { title: "The Drapery Falls", artist: "Opeth", album: "Blackwater Park", year: 2001 }, genre: "Metal", duration: 628, score: 96, timestamp: new Date(now - 6 * hr).toISOString(), timestampMs: now - 6 * hr },
  { id: "ls-1702", username: "riku.records", deviceId: "AA7788990022", track: { title: "Aguas de Marco", artist: "Tom Jobim", album: "Matita Pere", year: 1973 }, genre: "World", duration: 178, score: 85, timestamp: new Date(now - 3 * day).toISOString(), timestampMs: now - 3 * day },
  { id: "ls-1703", username: "riku.records", deviceId: "AA7788990022", track: { title: "Ghost of Perdition", artist: "Opeth", album: "Ghost Reveries", year: 2005 }, genre: "Metal", duration: 635, score: 95, timestamp: new Date(now - 6 * day).toISOString(), timestampMs: now - 6 * day },
  { id: "ls-1704", username: "riku.records", deviceId: "AA7788990022", track: { title: "Windowpane", artist: "Opeth", album: "Damnation", year: 2003 }, genre: "Rock", duration: 447, score: 93, timestamp: new Date(now - 10 * day).toISOString(), timestampMs: now - 10 * day },

  // ── cass.stacks — 4 sessions ──────────────────────────────────────────────
  { id: "ls-1801", username: "cass.stacks", deviceId: "BB8899001133", track: { title: "Rise Above", artist: "Black Flag", album: "Damaged", year: 1981 }, genre: "Punk", duration: 131, score: 95, timestamp: new Date(now - 4 * hr).toISOString(), timestampMs: now - 4 * hr },
  { id: "ls-1802", username: "cass.stacks", deviceId: "BB8899001133", track: { title: "Damaged Goods", artist: "Gang of Four", album: "Entertainment!", year: 1979 }, genre: "Punk", duration: 215, score: 91, timestamp: new Date(now - 1.5 * day).toISOString(), timestampMs: now - 1.5 * day },
  { id: "ls-1803", username: "cass.stacks", deviceId: "BB8899001133", track: { title: "White Riot", artist: "The Clash", album: "The Clash", year: 1977 }, genre: "Punk", duration: 118, score: 93, timestamp: new Date(now - 4 * day).toISOString(), timestampMs: now - 4 * day },
  { id: "ls-1804", username: "cass.stacks", deviceId: "BB8899001133", track: { title: "Blitzkrieg Bop", artist: "Ramones", album: "Ramones", year: 1976 }, genre: "Punk", duration: 135, score: 94, timestamp: new Date(now - 7 * day).toISOString(), timestampMs: now - 7 * day },

  // ── milo.vinyl — 4 sessions ───────────────────────────────────────────────
  { id: "ls-1901", username: "milo.vinyl", deviceId: "CC9900112244", track: { title: "River Man", artist: "Nick Drake", album: "Five Leaves Left", year: 1969 }, genre: "Folk", duration: 266, score: 93, timestamp: new Date(now - 8 * hr).toISOString(), timestampMs: now - 8 * hr },
  { id: "ls-1902", username: "milo.vinyl", deviceId: "CC9900112244", track: { title: "Skinny Love", artist: "Bon Iver", album: "For Emma, Forever Ago", year: 2007 }, genre: "Folk", duration: 226, score: 89, timestamp: new Date(now - 2.5 * day).toISOString(), timestampMs: now - 2.5 * day },
  { id: "ls-1903", username: "milo.vinyl", deviceId: "CC9900112244", track: { title: "Cactus Tree", artist: "Joni Mitchell", album: "Song to a Seagull", year: 1968 }, genre: "Folk", duration: 287, score: 91, timestamp: new Date(now - 5 * day).toISOString(), timestampMs: now - 5 * day },
  { id: "ls-1904", username: "milo.vinyl", deviceId: "CC9900112244", track: { title: "Pancho and Lefty", artist: "Townes Van Zandt", album: "The Late Great Townes Van Zandt", year: 1972 }, genre: "Folk", duration: 292, score: 95, timestamp: new Date(now - 8 * day).toISOString(), timestampMs: now - 8 * day },

  // ── petra.spins — 4 sessions ──────────────────────────────────────────────
  { id: "ls-2001", username: "petra.spins", deviceId: "DD0011223355", track: { title: "Goldberg Variations: Aria", artist: "Glenn Gould", album: "Goldberg Variations", year: 1955 }, genre: "Classical", duration: 198, score: 97, timestamp: new Date(now - 10 * hr).toISOString(), timestampMs: now - 10 * hr },
  { id: "ls-2002", username: "petra.spins", deviceId: "DD0011223355", track: { title: "Gymnopedies No. 1", artist: "Erik Satie", album: "Gymnopedies", year: 1888 }, genre: "Classical", duration: 198, score: 88, timestamp: new Date(now - 3 * day).toISOString(), timestampMs: now - 3 * day },
  { id: "ls-2003", username: "petra.spins", deviceId: "DD0011223355", track: { title: "Clair de Lune", artist: "Claude Debussy", album: "Suite bergamasque", year: 1905 }, genre: "Classical", duration: 312, score: 95, timestamp: new Date(now - 6 * day).toISOString(), timestampMs: now - 6 * day },
  { id: "ls-2004", username: "petra.spins", deviceId: "DD0011223355", track: { title: "The Four Seasons: Spring", artist: "Antonio Vivaldi", album: "The Four Seasons", year: 1725 }, genre: "Classical", duration: 625, score: 92, timestamp: new Date(now - 10 * day).toISOString(), timestampMs: now - 10 * day },

  // ── nico.crates — 3 sessions ──────────────────────────────────────────────
  { id: "ls-2101", username: "nico.crates", deviceId: "EE0011223366", track: { title: "The Girl from Ipanema", artist: "Stan Getz & Joao Gilberto", album: "Getz/Gilberto", year: 1964 }, genre: "Jazz", duration: 327, score: 94, timestamp: new Date(now - 5 * hr).toISOString(), timestampMs: now - 5 * hr },
  { id: "ls-2102", username: "nico.crates", deviceId: "EE0011223366", track: { title: "Tropicalia", artist: "Caetano Veloso", album: "Tropicalia", year: 1968 }, genre: "World", duration: 178, score: 91, timestamp: new Date(now - 2 * day).toISOString(), timestampMs: now - 2 * day },
  { id: "ls-2103", username: "nico.crates", deviceId: "EE0011223366", track: { title: "Mas Que Nada", artist: "Jorge Ben Jor", album: "Samba Esquema Novo", year: 1963 }, genre: "World", duration: 176, score: 93, timestamp: new Date(now - 5 * day).toISOString(), timestampMs: now - 5 * day },

  // ── ada.tracks — 3 sessions ───────────────────────────────────────────────
  { id: "ls-2201", username: "ada.tracks", deviceId: "FF0011223377", track: { title: "Untitled (How Does It Feel)", artist: "D'Angelo", album: "Voodoo", year: 2000 }, genre: "R&B", duration: 400, score: 97, timestamp: new Date(now - 8 * hr).toISOString(), timestampMs: now - 8 * hr },
  { id: "ls-2202", username: "ada.tracks", deviceId: "FF0011223377", track: { title: "Thinkin Bout You", artist: "Frank Ocean", album: "Channel Orange", year: 2012 }, genre: "R&B", duration: 200, score: 92, timestamp: new Date(now - 3 * day).toISOString(), timestampMs: now - 3 * day },
  { id: "ls-2203", username: "ada.tracks", deviceId: "FF0011223377", track: { title: "On & On", artist: "Erykah Badu", album: "Baduizm", year: 1997 }, genre: "R&B", duration: 278, score: 95, timestamp: new Date(now - 6 * day).toISOString(), timestampMs: now - 6 * day },

  // ── kai.wax — 3 sessions ──────────────────────────────────────────────────
  { id: "ls-2301", username: "kai.wax", deviceId: "AA0011223388", track: { title: "Fake Plastic Trees", artist: "Radiohead", album: "The Bends", year: 1995 }, genre: "Alternative", duration: 291, score: 95, timestamp: new Date(now - 4 * hr).toISOString(), timestampMs: now - 4 * hr },
  { id: "ls-2302", username: "kai.wax", deviceId: "AA0011223388", track: { title: "Hallogallo", artist: "Neu!", album: "Neu!", year: 1972 }, genre: "Experimental", duration: 600, score: 90, timestamp: new Date(now - 3 * day).toISOString(), timestampMs: now - 3 * day },
  { id: "ls-2303", username: "kai.wax", deviceId: "AA0011223388", track: { title: "Reckoner", artist: "Radiohead", album: "In Rainbows", year: 2007 }, genre: "Alternative", duration: 290, score: 96, timestamp: new Date(now - 7 * day).toISOString(), timestampMs: now - 7 * day },

  // ── sol.spins — 3 sessions ────────────────────────────────────────────────
  { id: "ls-2401", username: "sol.spins", deviceId: "BB0011223399", track: { title: "Zombie", artist: "Fela Kuti", album: "Zombie", year: 1977 }, genre: "World", duration: 732, score: 97, timestamp: new Date(now - 6 * hr).toISOString(), timestampMs: now - 6 * hr },
  { id: "ls-2402", username: "sol.spins", deviceId: "BB0011223399", track: { title: "Ye Ye De Smell", artist: "Fela Kuti", album: "Expensive Shit", year: 1975 }, genre: "World", duration: 815, score: 95, timestamp: new Date(now - 4 * day).toISOString(), timestampMs: now - 4 * day },
  { id: "ls-2403", username: "sol.spins", deviceId: "BB0011223399", track: { title: "Sweet Mother", artist: "Prince Nico Mbarga", album: "Sweet Mother", year: 1976 }, genre: "World", duration: 310, score: 89, timestamp: new Date(now - 8 * day).toISOString(), timestampMs: now - 8 * day },

  // ── tova.vinyl — 3 sessions ───────────────────────────────────────────────
  { id: "ls-2501", username: "tova.vinyl", deviceId: "CC0011223300", track: { title: "Summertime", artist: "Ella Fitzgerald & Louis Armstrong", album: "Porgy and Bess", year: 1957 }, genre: "Jazz", duration: 290, score: 96, timestamp: new Date(now - 9 * hr).toISOString(), timestampMs: now - 9 * hr },
  { id: "ls-2502", username: "tova.vinyl", deviceId: "CC0011223300", track: { title: "My Funny Valentine", artist: "Chet Baker", album: "Chet Baker Sings", year: 1954 }, genre: "Jazz", duration: 145, score: 94, timestamp: new Date(now - 3 * day).toISOString(), timestampMs: now - 3 * day },
  { id: "ls-2503", username: "tova.vinyl", deviceId: "CC0011223300", track: { title: "In the Wee Small Hours of the Morning", artist: "Frank Sinatra", album: "In the Wee Small Hours", year: 1955 }, genre: "Jazz", duration: 185, score: 97, timestamp: new Date(now - 7 * day).toISOString(), timestampMs: now - 7 * day },

  // ── wren.stacks — 3 sessions ──────────────────────────────────────────────
  { id: "ls-2601", username: "wren.stacks", deviceId: "DD0011223311", track: { title: "Robot Stop", artist: "King Gizzard & The Lizard Wizard", album: "Nonagon Infinity", year: 2016 }, genre: "Rock", duration: 175, score: 94, timestamp: new Date(now - 3 * hr).toISOString(), timestampMs: now - 3 * hr },
  { id: "ls-2602", username: "wren.stacks", deviceId: "DD0011223311", track: { title: "Finger", artist: "Ty Segall", album: "Manipulator", year: 2014 }, genre: "Rock", duration: 219, score: 90, timestamp: new Date(now - 2 * day).toISOString(), timestampMs: now - 2 * day },
  { id: "ls-2603", username: "wren.stacks", deviceId: "DD0011223311", track: { title: "Maria Tambien", artist: "Khruangbin", album: "Con Todo El Mundo", year: 2018 }, genre: "Rock", duration: 239, score: 92, timestamp: new Date(now - 6 * day).toISOString(), timestampMs: now - 6 * day },

  // ── romy.rpm — 3 sessions ─────────────────────────────────────────────────
  { id: "ls-2701", username: "romy.rpm", deviceId: "EE0011223322", track: { title: "Enjoy the Silence", artist: "Depeche Mode", album: "Violator", year: 1990 }, genre: "Pop", duration: 366, score: 96, timestamp: new Date(now - 7 * hr).toISOString(), timestampMs: now - 7 * hr },
  { id: "ls-2702", username: "romy.rpm", deviceId: "EE0011223322", track: { title: "Just Like Heaven", artist: "The Cure", album: "Kiss Me, Kiss Me, Kiss Me", year: 1987 }, genre: "Alternative", duration: 212, score: 94, timestamp: new Date(now - 3 * day).toISOString(), timestampMs: now - 3 * day },
  { id: "ls-2703", username: "romy.rpm", deviceId: "EE0011223322", track: { title: "Tainted Love", artist: "Soft Cell", album: "Non-Stop Erotic Cabaret", year: 1981 }, genre: "Pop", duration: 157, score: 91, timestamp: new Date(now - 7 * day).toISOString(), timestampMs: now - 7 * day },

  // ── hal.grooves — 3 sessions ──────────────────────────────────────────────
  { id: "ls-2801", username: "hal.grooves", deviceId: "FF0011223333", track: { title: "Cross Road Blues", artist: "Robert Johnson", album: "King of the Delta Blues Singers", year: 1936 }, genre: "Blues", duration: 168, score: 97, timestamp: new Date(now - 5 * hr).toISOString(), timestampMs: now - 5 * hr },
  { id: "ls-2802", username: "hal.grooves", deviceId: "FF0011223333", track: { title: "The Thrill Is Gone", artist: "B.B. King", album: "Completely Well", year: 1969 }, genre: "Blues", duration: 325, score: 95, timestamp: new Date(now - 2 * day).toISOString(), timestampMs: now - 2 * day },
  { id: "ls-2803", username: "hal.grooves", deviceId: "FF0011223333", track: { title: "Hoochie Coochie Man", artist: "Muddy Waters", album: "The Best of Muddy Waters", year: 1954 }, genre: "Blues", duration: 178, score: 93, timestamp: new Date(now - 6 * day).toISOString(), timestampMs: now - 6 * day },

  // ── june.vinyl — 3 sessions ───────────────────────────────────────────────
  { id: "ls-2901", username: "june.vinyl", deviceId: "AA0011223344", track: { title: "Untitled (How Does It Feel)", artist: "D'Angelo", album: "Voodoo", year: 2000 }, genre: "R&B", duration: 400, score: 98, timestamp: new Date(now - 4 * hr).toISOString(), timestampMs: now - 4 * hr },
  { id: "ls-2902", username: "june.vinyl", deviceId: "AA0011223344", track: { title: "On & On", artist: "Erykah Badu", album: "Baduizm", year: 1997 }, genre: "R&B", duration: 278, score: 96, timestamp: new Date(now - 2 * day).toISOString(), timestampMs: now - 2 * day },
  { id: "ls-2903", username: "june.vinyl", deviceId: "AA0011223344", track: { title: "Golden", artist: "Jill Scott", album: "Beautifully Human", year: 2004 }, genre: "R&B", duration: 245, score: 93, timestamp: new Date(now - 5 * day).toISOString(), timestampMs: now - 5 * day },

  // ── arlo.wax — 3 sessions ─────────────────────────────────────────────────
  { id: "ls-3001", username: "arlo.wax", deviceId: "BB0011223355", track: { title: "Pancho and Lefty", artist: "Townes Van Zandt", album: "The Late Great Townes Van Zandt", year: 1972 }, genre: "Country", duration: 292, score: 96, timestamp: new Date(now - 6 * hr).toISOString(), timestampMs: now - 6 * hr },
  { id: "ls-3002", username: "arlo.wax", deviceId: "BB0011223355", track: { title: "Blue Eyes Crying in the Rain", artist: "Willie Nelson", album: "Red Headed Stranger", year: 1975 }, genre: "Country", duration: 143, score: 94, timestamp: new Date(now - 3 * day).toISOString(), timestampMs: now - 3 * day },
  { id: "ls-3003", username: "arlo.wax", deviceId: "BB0011223355", track: { title: "Mama Tried", artist: "Merle Haggard", album: "Mama Tried", year: 1968 }, genre: "Country", duration: 152, score: 92, timestamp: new Date(now - 7 * day).toISOString(), timestampMs: now - 7 * day },

  // ── emi.spins — 3 sessions ────────────────────────────────────────────────
  { id: "ls-3101", username: "emi.spins", deviceId: "CC0011223366", track: { title: "Music for 18 Musicians: Section I", artist: "Steve Reich", album: "Music for 18 Musicians", year: 1978 }, genre: "Classical", duration: 720, score: 98, timestamp: new Date(now - 8 * hr).toISOString(), timestampMs: now - 8 * hr },
  { id: "ls-3102", username: "emi.spins", deviceId: "CC0011223366", track: { title: "d.p. 1.1", artist: "William Basinski", album: "The Disintegration Loops", year: 2002 }, genre: "Electronic", duration: 3780, score: 94, timestamp: new Date(now - 4 * day).toISOString(), timestampMs: now - 4 * day },
  { id: "ls-3103", username: "emi.spins", deviceId: "CC0011223366", track: { title: "Different Trains: America, Before the War", artist: "Steve Reich", album: "Different Trains", year: 1988 }, genre: "Classical", duration: 540, score: 96, timestamp: new Date(now - 9 * day).toISOString(), timestampMs: now - 9 * day },

  // ── vince.rpm — 2 sessions ────────────────────────────────────────────────
  { id: "ls-3201", username: "vince.rpm", deviceId: "DD0011223377", track: { title: "Low Rider", artist: "War", album: "Why Can't We Be Friends?", year: 1975 }, genre: "Funk", duration: 215, score: 95, timestamp: new Date(now - 10 * hr).toISOString(), timestampMs: now - 10 * hr },
  { id: "ls-3202", username: "vince.rpm", deviceId: "DD0011223377", track: { title: "Whittier Blvd", artist: "Thee Midniters", album: "Whittier Blvd", year: 1965 }, genre: "Soul", duration: 152, score: 91, timestamp: new Date(now - 4 * day).toISOString(), timestampMs: now - 4 * day },

  // ── freya.wax — 2 sessions ────────────────────────────────────────────────
  { id: "ls-3301", username: "freya.wax", deviceId: "EE0011223388", track: { title: "Parce Mihi Domine", artist: "Jan Garbarek & The Hilliard Ensemble", album: "Officium", year: 1994 }, genre: "Jazz", duration: 487, score: 96, timestamp: new Date(now - 12 * hr).toISOString(), timestampMs: now - 12 * hr },
  { id: "ls-3302", username: "freya.wax", deviceId: "EE0011223388", track: { title: "Belong", artist: "Bobo Stenson Trio", album: "Serenity", year: 2000 }, genre: "Jazz", duration: 356, score: 92, timestamp: new Date(now - 5 * day).toISOString(), timestampMs: now - 5 * day },

  // ── dante.grooves — 2 sessions ────────────────────────────────────────────
  { id: "ls-3401", username: "dante.grooves", deviceId: "FF0011223399", track: { title: "Suspiria", artist: "Goblin", album: "Suspiria", year: 1977 }, genre: "Rock", duration: 421, score: 95, timestamp: new Date(now - 9 * hr).toISOString(), timestampMs: now - 9 * hr },
  { id: "ls-3402", username: "dante.grooves", deviceId: "FF0011223399", track: { title: "Celebration", artist: "Premiata Forneria Marconi", album: "Photos of Ghosts", year: 1973 }, genre: "Rock", duration: 378, score: 92, timestamp: new Date(now - 4 * day).toISOString(), timestampMs: now - 4 * day },

  // ── theo.plays — 2 sessions ───────────────────────────────────────────────
  { id: "ls-3501", username: "theo.plays", deviceId: "AA0011223300", track: { title: "Bustin' Loose", artist: "Chuck Brown & The Soul Searchers", album: "Bustin' Loose", year: 1978 }, genre: "Funk", duration: 489, score: 97, timestamp: new Date(now - 7 * hr).toISOString(), timestampMs: now - 7 * hr },
  { id: "ls-3502", username: "theo.plays", deviceId: "AA0011223300", track: { title: "We Need Some Money", artist: "Chuck Brown", album: "Any Other Way to Go?", year: 1985 }, genre: "Funk", duration: 325, score: 93, timestamp: new Date(now - 3 * day).toISOString(), timestampMs: now - 3 * day },

  // ── maya.tracks — 2 sessions ──────────────────────────────────────────────
  { id: "ls-3601", username: "maya.tracks", deviceId: "BB0011223311", track: { title: "Journey in Satchidananda", artist: "Alice Coltrane", album: "Journey in Satchidananda", year: 1971 }, genre: "Jazz", duration: 398, score: 98, timestamp: new Date(now - 5 * hr).toISOString(), timestampMs: now - 5 * hr },
  { id: "ls-3602", username: "maya.tracks", deviceId: "BB0011223311", track: { title: "Amazing Grace", artist: "Aretha Franklin", album: "Amazing Grace", year: 1972 }, genre: "Soul", duration: 612, score: 96, timestamp: new Date(now - 4 * day).toISOString(), timestampMs: now - 4 * day },

  // ── liam.stacks — 2 sessions ──────────────────────────────────────────────
  { id: "ls-3701", username: "liam.stacks", deviceId: "CC0011223322", track: { title: "Nightcall", artist: "Kavinsky", album: "OutRun", year: 2013 }, genre: "Electronic", duration: 253, score: 94, timestamp: new Date(now - 11 * hr).toISOString(), timestampMs: now - 11 * hr },
  { id: "ls-3702", username: "liam.stacks", deviceId: "CC0011223322", track: { title: "Tech Noir", artist: "Gunship", album: "Gunship", year: 2015 }, genre: "Electronic", duration: 310, score: 91, timestamp: new Date(now - 5 * day).toISOString(), timestampMs: now - 5 * day },
];

export default INITIAL_LISTENING;
