// Seed data for the social feed — user-created posts with optional tagged records.
// Posts are separate from the record catalog; they're social content that can reference any record.
// Shape: { id, user, type, caption, mediaUrl?, mediaType, taggedRecord?, likes, liked, comments[], bookmarked, timeAgo, createdAt, accent, reactions, views }

const now = Date.now();
const hr = 3600000;
const day = 86400000;

// Generate deterministic reaction counts and view counts for posts
const _reactionSeed = (id) => {
  const base = ((id * 7) % 30) + 2;
  return { fire: base, heart: Math.floor(base * 0.7), vinyl: Math.floor(base * 0.4) };
};
const _viewSeed = (id) => ((id * 13) % 400) + 80;

const INITIAL_POSTS = [
  {
    id: 2001,
    user: "mara.vinyl",
    type: "review",
    caption: "Found this original Impulse! pressing at a garage sale for $3. The vinyl gods were smiling today. The deep groove pressing sounds absolutely incredible through the Ortofon 2M Blue.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "A Love Supreme", artist: "John Coltrane" },
    likes: 34,
    liked: false,
    comments: [
      { id: 1, user: "felix.rpm", text: "No way!! That's an incredible find! \uD83D\uDD25", time: "3h ago" },
      { id: 2, user: "yuki.vinyl", text: "The vinyl gods indeed. I've been hunting this for years.", time: "2h ago" },
      { id: 3, user: "soren.stacks", text: "Deep groove Impulse pressings are the holy grail. Congrats!", time: "1h ago" },
    ],
    bookmarked: false,
    timeAgo: "4h ago",
    createdAt: now - 4 * hr,
    accent: "#ec4899",
    reactions: { fire: 12, heart: 8, vinyl: 5 },
    views: 287,
  },
  {
    id: 2002,
    user: "nadia.rpm",
    type: "review",
    caption: "Saturday morning ritual. Coffee, this record, and absolutely nothing else. Hip-hop doesn't get more perfect than this.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Illmatic", artist: "Nas" },
    likes: 47,
    liked: false,
    comments: [
      { id: 4, user: "dax.wax", text: "The greatest hip-hop album ever made. No debate.", time: "5h ago" },
      { id: 5, user: "max.plays", text: "Every single track is a 10/10", time: "4h ago" },
    ],
    bookmarked: false,
    timeAgo: "6h ago",
    createdAt: now - 6 * hr,
    accent: "#8b5cf6",
  },
  {
    id: 2003,
    user: "juniper.sounds",
    type: "photo",
    caption: "Just reorganized my entire electronic section by BPM instead of alphabetically. Is this what going too far looks like? Anyway here's the crown jewel of the collection.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Selected Ambient Works 85-92", artist: "Aphex Twin" },
    likes: 29,
    liked: false,
    comments: [
      { id: 6, user: "beau.plays", text: "Organizing by BPM is galaxy brain actually", time: "8h ago" },
      { id: 7, user: "otto.wax", text: "I organize mine by mood. We are not the same.", time: "7h ago" },
    ],
    bookmarked: false,
    timeAgo: "9h ago",
    createdAt: now - 9 * hr,
    accent: "#f97316",
  },
  {
    id: 2004,
    user: "thomas.wax",
    type: "photo",
    caption: "My turntable setup got a major upgrade today. New Rega Planar 3 with an Exact cartridge. First spin had to be the classics. The separation on this pressing is unreal.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Led Zeppelin IV", artist: "Led Zeppelin" },
    likes: 52,
    liked: false,
    comments: [
      { id: 8, user: "bjorn.grooves", text: "Rega Planar 3 is incredible for the price. Great choice!", time: "10h ago" },
      { id: 9, user: "iris.rpm", text: "The acoustic guitar on Going to California through a good setup... *chefs kiss*", time: "9h ago" },
      { id: 10, user: "thomas.wax", text: "Exactly!! And the dynamics on When the Levee Breaks \uD83E\uDD2F", time: "8h ago" },
    ],
    bookmarked: false,
    timeAgo: "11h ago",
    createdAt: now - 11 * hr,
    accent: "#a78bfa",
  },
  {
    id: 2005,
    user: "yuki.vinyl",
    type: "review",
    caption: "City pop deep cut alert. Picked this up in Shibuya last month. The bass line on side B is pure serotonin. If you know, you know. #citypop #japanesevinyl",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Pacific", artist: "Haruomi Hosono" },
    likes: 38,
    liked: false,
    comments: [
      { id: 11, user: "juniper.sounds", text: "City pop on vinyl hits different. That warm analog sound!", time: "12h ago" },
      { id: 12, user: "mara.vinyl", text: "Adding this to my want list immediately", time: "11h ago" },
    ],
    bookmarked: false,
    timeAgo: "14h ago",
    createdAt: now - 14 * hr,
    accent: "#f59e0b",
  },
  {
    id: 2006,
    user: "cleo.spins",
    type: "review",
    caption: "Shoegaze Sunday. Turned the lights off, cranked the volume, and let the noise wash over me. This album is a religious experience on vinyl. #shoegaze #sundaylistening",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Loveless", artist: "My Bloody Valentine" },
    likes: 41,
    liked: false,
    comments: [
      { id: 13, user: "otto.wax", text: "The way the guitars blur together on Only Shallow... transcendent", time: "16h ago" },
      { id: 14, user: "cass.stacks", text: "Best album ever made. Fight me.", time: "15h ago" },
    ],
    bookmarked: false,
    timeAgo: "18h ago",
    createdAt: now - 18 * hr,
    accent: "#84cc16",
  },
  {
    id: 2007,
    user: "max.plays",
    type: "review",
    caption: "Store pickup of the week! Customer brought in a box of records and this was hiding at the bottom. Original pressing, plays clean. Sometimes the best crates find you.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Maggot Brain", artist: "Funkadelic" },
    likes: 56,
    liked: false,
    comments: [
      { id: 15, user: "dax.wax", text: "That opening guitar solo is 10 minutes of pure emotion", time: "20h ago" },
      { id: 16, user: "lena.records", text: "Eddie Hazel played that solo as if his mother just died. Because George Clinton told him to imagine that.", time: "19h ago" },
      { id: 17, user: "felix.rpm", text: "One of the greatest guitar performances ever recorded", time: "18h ago" },
    ],
    bookmarked: false,
    timeAgo: "22h ago",
    createdAt: now - 22 * hr,
    accent: "#a78bfa",
  },
  {
    id: 2008,
    user: "felix.rpm",
    type: "review",
    caption: "Late night jazz session. There's something about Herbie's Rhodes playing on this album that just puts you in another dimension. The Headhunters were so tight.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Head Hunters", artist: "Herbie Hancock" },
    likes: 33,
    liked: false,
    comments: [
      { id: 18, user: "mara.vinyl", text: "Chameleon is the song that got me into jazz. Forever grateful.", time: "1d ago" },
      { id: 19, user: "soren.stacks", text: "Jazz-funk perfection. Every musician should study this album.", time: "1d ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 1 * day,
    accent: "#06b6d4",
  },
  {
    id: 2009,
    user: "otto.wax",
    type: "photo",
    caption: "Berlin flea market haul. Found a German pressing of Unknown Pleasures with the textured sleeve intact. Peter Saville's cover design is even more stunning in person.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Unknown Pleasures", artist: "Joy Division" },
    likes: 44,
    liked: false,
    comments: [
      { id: 20, user: "cass.stacks", text: "German pressings sound incredible. Factory Records quality.", time: "1d ago" },
      { id: 21, user: "cleo.spins", text: "That cover is literally hanging on my wall as a poster", time: "1d ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 28 * hr,
    accent: "#ef4444",
  },
  {
    id: 2010,
    user: "lena.records",
    type: "review",
    caption: "What's Going On was released 55 years ago and every word still hits. Marvin was ahead of his time. This is the album I play when the world feels heavy. #soul #classic",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "What's Going On", artist: "Marvin Gaye" },
    likes: 61,
    liked: false,
    comments: [
      { id: 22, user: "nadia.rpm", text: "Timeless. One of the most important albums ever made.", time: "1d ago" },
      { id: 23, user: "max.plays", text: "The string arrangements on this album are absolutely gorgeous", time: "1d ago" },
      { id: 24, user: "zara.grooves", text: "Mercy Mercy Me still gives me chills every time", time: "1d ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 32 * hr,
    accent: "#ec4899",
  },
  {
    id: 2011,
    user: "bjorn.grooves",
    type: "review",
    caption: "Finally got my hands on a clean copy. The riffs on this record literally invented a genre. Played it three times back to back and my neighbors are not happy. \uD83E\uDD18",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Master of Puppets", artist: "Metallica" },
    likes: 39,
    liked: false,
    comments: [
      { id: 25, user: "riku.records", text: "GOAT metal album. Orion alone makes it a masterpiece.", time: "2d ago" },
      { id: 26, user: "thomas.wax", text: "Even as a rock guy I can appreciate the musicianship here", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 2 * day,
    accent: "#10b981",
  },
  {
    id: 2012,
    user: "beau.plays",
    type: "review",
    caption: "Every Friday night needs a proper warm-up. This is mine. French house forever. The sample work on this album changed dance music. \uD83C\uDFA7",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Homework", artist: "Daft Punk" },
    likes: 45,
    liked: false,
    comments: [
      { id: 27, user: "juniper.sounds", text: "Da Funk into Rollin & Scratchin is the best 1-2 punch in electronic music", time: "2d ago" },
      { id: 28, user: "beau.plays", text: "Absolutely! The energy never drops", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 50 * hr,
    accent: "#f59e0b",
  },
  {
    id: 2013,
    user: "milo.vinyl",
    type: "review",
    caption: "Rainy afternoon, hot tea, and Nick Drake. This is what vinyl was made for. The intimacy of Pink Moon on a good system is unmatched.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Pink Moon", artist: "Nick Drake" },
    likes: 28,
    liked: false,
    comments: [
      { id: 29, user: "cleo.spins", text: "Nick Drake's voice in a quiet room is pure therapy", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 3 * day,
    accent: "#84cc16",
  },
  {
    id: 2014,
    user: "dax.wax",
    type: "review",
    caption: "Dollar bin treasure! Found this absolute gem for $0.50. The cover is beat up but the record plays VG+. This is why I dig. You never know what's hiding in those cheap bins. #cratedigging #dollarbin",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "There's a Riot Goin' On", artist: "Sly & The Family Stone" },
    likes: 36,
    liked: false,
    comments: [
      { id: 30, user: "max.plays", text: "Dollar bin king strikes again! Great find.", time: "3d ago" },
      { id: 31, user: "lena.records", text: "Family Affair is such a vibe. Incredible album.", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 75 * hr,
    accent: "#06b6d4",
  },
  {
    id: 2015,
    user: "zara.grooves",
    type: "review",
    caption: "Turned my living room into Kingston for the evening. Burning incense, this on the turntable, and nowhere to be. Pure bliss. \uD83C\uDDEF\uD83C\uDDF2",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Catch a Fire", artist: "Bob Marley & The Wailers" },
    likes: 31,
    liked: false,
    comments: [
      { id: 32, user: "felix.rpm", text: "Island Records pressings of the Wailers stuff sound so good!", time: "4d ago" },
    ],
    bookmarked: false,
    timeAgo: "4d ago",
    createdAt: now - 4 * day,
    accent: "#10b981",
  },
  {
    id: 2016,
    user: "creator",
    type: "photo",
    caption: "Finally pulled the trigger on a proper cleaning setup. Spin-Clean record washer + new inner sleeves for the whole collection. Spent all weekend cleaning and re-sleeving. My records have never sounded this good.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 22,
    liked: false,
    comments: [
      { id: 33, user: "thomas.wax", text: "Spin-Clean is the best $80 you can spend in this hobby", time: "1h ago" },
      { id: 34, user: "mara.vinyl", text: "MoFi inner sleeves are the way. Congrats on the upgrade!", time: "45m ago" },
    ],
    bookmarked: false,
    timeAgo: "2h ago",
    createdAt: now - 2 * hr,
    accent: "#0ea5e9",
  },
  {
    id: 2017,
    user: "creator",
    type: "review",
    caption: "Just picked this up from the local shop. The six-eye Columbia mono pressing. Forty years of searching and it finally happened. My hands are still shaking.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Kind of Blue", artist: "Miles Davis" },
    likes: 78,
    liked: false,
    comments: [
      { id: 35, user: "mara.vinyl", text: "SIX-EYE MONO?! I'm genuinely jealous. Congratulations!", time: "5h ago" },
      { id: 36, user: "felix.rpm", text: "That might be the single greatest jazz pressing you can own", time: "4h ago" },
      { id: 37, user: "soren.stacks", text: "The holy grail. Enjoy every second of it.", time: "3h ago" },
      { id: 38, user: "yuki.vinyl", text: "I need to hear this. Next time I'm in town, I'm coming over.", time: "2h ago" },
    ],
    bookmarked: false,
    timeAgo: "6h ago",
    createdAt: now - 6 * hr,
    accent: "#0ea5e9",
  },
  {
    id: 2018,
    user: "petra.spins",
    type: "review",
    caption: "The Goldberg Variations on vinyl is a completely different experience from digital. You can hear Glenn Gould humming along. The analog warmth makes the piano sound so much more present.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Goldberg Variations", artist: "Glenn Gould" },
    likes: 19,
    liked: false,
    comments: [
      { id: 39, user: "soren.stacks", text: "Gould's humming is half the charm. A truly intimate recording.", time: "6h ago" },
    ],
    bookmarked: false,
    timeAgo: "8h ago",
    createdAt: now - 8 * hr,
    accent: "#ef4444",
  },
  {
    id: 2019,
    user: "riku.records",
    type: "review",
    caption: "Hot take: Blackwater Park is Opeth's best album and it's not even close. The dynamics between the quiet acoustic sections and the crushing heaviness are unmatched in metal. \uD83E\uDD18\uD83C\uDFB8",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Blackwater Park", artist: "Opeth" },
    likes: 27,
    liked: false,
    comments: [
      { id: 40, user: "bjorn.grooves", text: "This is not a hot take, it's just facts. The Drapery Falls is transcendent.", time: "10h ago" },
      { id: 41, user: "cass.stacks", text: "Still Life is close but yeah, this one edges it out", time: "9h ago" },
    ],
    bookmarked: false,
    timeAgo: "12h ago",
    createdAt: now - 12 * hr,
    accent: "#8b5cf6",
  },
  {
    id: 2020,
    user: "soren.stacks",
    type: "review",
    caption: "Quiet evening in Copenhagen. Rain on the windows and this on the turntable. There is no better ambient album. The textures are so delicate they almost disappear.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Music for Airports", artist: "Brian Eno" },
    likes: 24,
    liked: false,
    comments: [
      { id: 42, user: "juniper.sounds", text: "Eno basically invented ambient music with this record. Timeless.", time: "14h ago" },
      { id: 43, user: "mara.vinyl", text: "I fall asleep to this at least once a week. In the best way.", time: "13h ago" },
    ],
    bookmarked: false,
    timeAgo: "16h ago",
    createdAt: now - 16 * hr,
    accent: "#0ea5e9",
  },
  {
    id: 2021,
    user: "iris.rpm",
    type: "review",
    caption: "Unpopular opinion: Tales from Topographic Oceans is actually good. Yes, all four sides. I will not be taking questions at this time. #progrock",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Tales from Topographic Oceans", artist: "Yes" },
    likes: 15,
    liked: false,
    comments: [
      { id: 44, user: "thomas.wax", text: "I respect the commitment even if I can't make it past side two", time: "1d ago" },
      { id: 45, user: "riku.records", text: "Prog heads unite. This album is a journey and I love every minute.", time: "1d ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 26 * hr,
    accent: "#f97316",
  },
  {
    id: 2022,
    user: "cass.stacks",
    type: "review",
    caption: "Just got back from a punk show at Whelan's and had to come home and put this on. Nothing sounds more alive than the first Clash album after a sweaty gig. \uD83E\uDD1C\uD83E\uDD1B",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "The Clash", artist: "The Clash" },
    likes: 33,
    liked: false,
    comments: [
      { id: 46, user: "otto.wax", text: "Post-show vinyl sessions are the best. What did you see?", time: "20h ago" },
      { id: 47, user: "cass.stacks", text: "Local band called The Drowning Men. Absolute chaos. Loved it.", time: "19h ago" },
    ],
    bookmarked: false,
    timeAgo: "22h ago",
    createdAt: now - 22 * hr,
    accent: "#0ea5e9",
  },
  {
    id: 2023,
    user: "creator",
    type: "photo",
    caption: "Three years of collecting and I just hit 500 records. Here's a shelf shot. Some of you might recognize a few grails in there. What a journey it's been. \uD83C\uDF89",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 91,
    liked: false,
    comments: [
      { id: 48, user: "max.plays", text: "500 club! Welcome. It only gets worse from here \uD83D\uDE05", time: "2d ago" },
      { id: 49, user: "dax.wax", text: "I see that Blue Note spine... is that an original Coltrane?", time: "2d ago" },
      { id: 50, user: "creator", text: "Good eye! Blue Train, deep groove pressing.", time: "2d ago" },
      { id: 51, user: "mara.vinyl", text: "Incredible collection. That top shelf is pure class.", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 2 * day,
    accent: "#0ea5e9",
  },
  {
    id: 2024,
    user: "nadia.rpm",
    type: "question",
    caption: "Question for the timeline: what's the one album that got you into vinyl? For me it was this. Heard it on a friend's turntable in college and never went back to streaming. #vinyljourney",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Ready to Die", artist: "The Notorious B.I.G." },
    likes: 58,
    liked: false,
    comments: [
      { id: 52, user: "thomas.wax", text: "Led Zeppelin IV at my uncle's house. Changed everything.", time: "1d ago" },
      { id: 53, user: "mara.vinyl", text: "Kind of Blue on my mom's old turntable. I was 14.", time: "1d ago" },
      { id: 54, user: "cleo.spins", text: "Siamese Dream. The guitar tones on vinyl were a revelation.", time: "1d ago" },
      { id: 55, user: "beau.plays", text: "Discovery by Daft Punk. The gatefold artwork sealed the deal.", time: "23h ago" },
      { id: 56, user: "lena.records", text: "Otis Redding - Otis Blue. My dad's copy. Still have it.", time: "22h ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 30 * hr,
    accent: "#8b5cf6",
  },
  {
    id: 2025,
    user: "juniper.sounds",
    type: "review",
    caption: "New Burial 12-inch arrived. The man continues to make music that sounds like 3am in a city you've never been to. Hyperdub never misses.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Untrue", artist: "Burial" },
    likes: 37,
    liked: false,
    comments: [
      { id: 57, user: "beau.plays", text: "Archangel on vinyl in a dark room is a spiritual experience", time: "3d ago" },
      { id: 58, user: "otto.wax", text: "3am in a city you've never been to is the most accurate description of Burial I've ever read", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 3 * day,
    accent: "#f97316",
  },
  {
    id: 2026,
    user: "lena.records",
    type: "review",
    caption: "Atlantic Records pressings from the late 60s just hit different. The mastering, the pressing quality, the cover art. They don't make them like this anymore.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "I Never Loved a Man the Way I Love You", artist: "Aretha Franklin" },
    likes: 43,
    liked: false,
    comments: [
      { id: 59, user: "max.plays", text: "Respect is the greatest vocal performance ever recorded. Change my mind.", time: "2d ago" },
      { id: 60, user: "zara.grooves", text: "Those Atlantic soul records are pure gold. Every one.", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 54 * hr,
    accent: "#ec4899",
  },
  {
    id: 2027,
    user: "max.plays",
    type: "trade",
    caption: "Priced some new arrivals for the shop today. Had to sit down and listen to this one before putting it on the shelf. Almost kept it for myself. Almost. #recordstore",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Standing on the Verge of Getting It On", artist: "Funkadelic" },
    likes: 29,
    liked: false,
    comments: [
      { id: 61, user: "dax.wax", text: "How much?? I'm on my way.", time: "4d ago" },
      { id: 62, user: "max.plays", text: "$35. First come first served. And no, I'm not holding it.", time: "4d ago" },
      { id: 63, user: "felix.rpm", text: "The title track is INSANE. One of the tightest funk performances ever.", time: "4d ago" },
    ],
    bookmarked: false,
    timeAgo: "4d ago",
    createdAt: now - 4 * day,
    accent: "#a78bfa",
  },
  {
    id: 2028,
    user: "yuki.vinyl",
    type: "photo",
    caption: "Spent the morning at Disk Union in Shibuya. The J-jazz section there is unbelievable. Walked out with five records and an empty wallet. Zero regrets. \uD83C\uDDEF\uD83C\uDDF5 #digunion #jjazz",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 42,
    liked: false,
    comments: [
      { id: 64, user: "mara.vinyl", text: "Disk Union is vinyl paradise. I'm so jealous you get to go regularly.", time: "5d ago" },
      { id: 65, user: "soren.stacks", text: "What did you pick up? Drop the haul!", time: "5d ago" },
      { id: 66, user: "yuki.vinyl", text: "Ryo Fukui, Masabumi Kikuchi, Terumasa Hino, and two Sadao Watanabe records. All originals.", time: "5d ago" },
    ],
    bookmarked: false,
    timeAgo: "5d ago",
    createdAt: now - 5 * day,
    accent: "#f59e0b",
  },
  {
    id: 2029,
    user: "bjorn.grooves",
    type: "review",
    caption: "Controversial ranking time: Black Sabbath > Paranoid. The self-titled has a rawness that Paranoid polished away. Both are masterpieces but the debut is where it all started.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Black Sabbath", artist: "Black Sabbath" },
    likes: 35,
    liked: false,
    comments: [
      { id: 67, user: "riku.records", text: "Absolutely correct. The self-titled invented doom metal in real time.", time: "3d ago" },
      { id: 68, user: "thomas.wax", text: "That opening tritone on Black Sabbath... still the heaviest riff ever written.", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 78 * hr,
    accent: "#10b981",
  },
  {
    id: 2030,
    user: "creator",
    type: "question",
    caption: "Anyone else find that certain records just sound better at specific times of day? This one is strictly a midnight record for me. Something about the atmosphere of Blonde at night.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Blonde", artist: "Frank Ocean" },
    likes: 64,
    liked: false,
    comments: [
      { id: 69, user: "nadia.rpm", text: "Blonde is 100% a 2am album. Nights hits differently when it's actually nighttime.", time: "1d ago" },
      { id: 70, user: "cleo.spins", text: "Self Control at midnight with headphones. That's the move.", time: "1d ago" },
      { id: 71, user: "juniper.sounds", text: "Morning records, afternoon records, evening records. We all do this right?", time: "23h ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 36 * hr,
    accent: "#0ea5e9",
  },
  {
    id: 2031,
    user: "dax.wax",
    type: "photo",
    caption: "Garage sale season is officially open. Hit four sales before 8am. Total haul: 23 records for $12. Quality? We'll see when I get home and clean them up. #garagesale #cratedigging",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 48,
    liked: false,
    comments: [
      { id: 72, user: "max.plays", text: "The early bird gets the wax. What neighborhoods?", time: "5d ago" },
      { id: 73, user: "dax.wax", text: "Southwest Detroit. Old Motown territory. You'd be surprised what turns up.", time: "5d ago" },
    ],
    bookmarked: false,
    timeAgo: "5d ago",
    createdAt: now - 126 * hr,
    accent: "#06b6d4",
  },
  {
    id: 2032,
    user: "mara.vinyl",
    type: "photo",
    caption: "Spent the afternoon deep-cleaning my jazz shelves. Re-organized by label instead of artist. Blue Note, Prestige, Impulse!, Riverside. Looks incredible. Sounds even better.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 26,
    liked: false,
    comments: [
      { id: 74, user: "felix.rpm", text: "Label organization is so satisfying. All those Blue Note spines lined up...", time: "6d ago" },
      { id: 75, user: "soren.stacks", text: "ECM section must look pristine with those clean white spines", time: "6d ago" },
    ],
    bookmarked: false,
    timeAgo: "6d ago",
    createdAt: now - 6 * day,
    accent: "#ec4899",
  },
  {
    id: 2033,
    user: "zara.grooves",
    type: "review",
    caption: "Lee Scratch Perry was a genius and I will never stop saying it. The production on this record sounds like it was beamed in from another planet. RIP the Upsetter.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Super Ape", artist: "Lee Scratch Perry" },
    likes: 30,
    liked: false,
    comments: [
      { id: 76, user: "felix.rpm", text: "The Black Ark studio recordings are some of the most creative music ever made", time: "4d ago" },
    ],
    bookmarked: false,
    timeAgo: "4d ago",
    createdAt: now - 102 * hr,
    accent: "#10b981",
  },
  {
    id: 2034,
    user: "beau.plays",
    type: "review",
    caption: "Saturday night in Paris. Friends over, turntable warm, and this on repeat. Disco is alive and well in this apartment. \uD83C\uDDEB\uD83C\uDDF7\uD83D\uDD7A",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Random Access Memories", artist: "Daft Punk" },
    likes: 51,
    liked: false,
    comments: [
      { id: 77, user: "juniper.sounds", text: "Giorgio by Moroder is the most fun track on any album ever", time: "1d ago" },
      { id: 78, user: "yuki.vinyl", text: "Touch still makes me emotional every single time", time: "1d ago" },
      { id: 79, user: "beau.plays", text: "Lose Yourself to Dance at volume is pure joy. The apartment was shaking.", time: "22h ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 39 * hr,
    accent: "#f59e0b",
  },
  {
    id: 2035,
    user: "otto.wax",
    type: "question",
    caption: "Does anyone else have a record they keep buying different pressings of? I now own four copies of Closer. The Factory original, the 2007 remaster, the 2015 remaster, and a Japanese pressing. I might have a problem.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Closer", artist: "Joy Division" },
    likes: 38,
    liked: false,
    comments: [
      { id: 80, user: "cleo.spins", text: "I have three copies of Loveless so I'm not judging", time: "2d ago" },
      { id: 81, user: "cass.stacks", text: "This is just collecting at an advanced level. Embrace it.", time: "2d ago" },
      { id: 82, user: "thomas.wax", text: "I have five Zep IVs. Different masterings, different magic.", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 57 * hr,
    accent: "#ef4444",
  },
  {
    id: 2036,
    user: "milo.vinyl",
    type: "review",
    caption: "First listen of the day. Coffee hasn't even kicked in yet. There's something about folk music in the morning that just feels right. The world is quiet and so is this record.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "For Emma, Forever Ago", artist: "Bon Iver" },
    likes: 21,
    liked: false,
    comments: [
      { id: 83, user: "cleo.spins", text: "Skinny Love on vinyl in the morning... that's meditation.", time: "6d ago" },
    ],
    bookmarked: false,
    timeAgo: "6d ago",
    createdAt: now - 150 * hr,
    accent: "#84cc16",
  },
  {
    id: 2037,
    user: "creator",
    type: "photo",
    caption: "Marketplace find: someone was selling their entire Warp Records collection. I grabbed what I could. Aphex Twin, Autechre, Boards of Canada, Squarepusher. Best $200 I've ever spent.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 55,
    liked: false,
    comments: [
      { id: 84, user: "juniper.sounds", text: "A WHOLE WARP COLLECTION? I'm genuinely upset I missed this.", time: "3d ago" },
      { id: 85, user: "beau.plays", text: "Boards of Canada on vinyl is a must. Which ones did you get?", time: "3d ago" },
      { id: 86, user: "creator", text: "Music Has the Right to Children and Geogaddi. Both NM.", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 78 * hr,
    accent: "#0ea5e9",
  },
  {
    id: 2038,
    user: "nico.crates",
    type: "announcement",
    caption: "New to GrooveStack! Just moved to LA and looking to connect with other collectors. My thing is 70s Brazilian music - bossa nova, tropicalia, MPB. Hit me up if you're into it. \uD83C\uDDE7\uD83C\uDDF7 #newhere #bossanova #tropicalia",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 18,
    liked: false,
    comments: [
      { id: 87, user: "felix.rpm", text: "Welcome! You need to check out the marketplace. Some great Brazilian records pop up.", time: "1d ago" },
      { id: 88, user: "yuki.vinyl", text: "Love bossa nova. What's your favorite Jobim record?", time: "1d ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 42 * hr,
    accent: "#f97316",
  },
  {
    id: 2039,
    user: "ada.tracks",
    type: "photo",
    caption: "Finally set up my listening room properly. Acoustic panels, dedicated circuit, and the turntable on a wall-mounted shelf to kill vibration. The difference is staggering. Every record sounds new again.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 40,
    liked: false,
    comments: [
      { id: 89, user: "thomas.wax", text: "Dedicated circuit is so underrated. Huge upgrade for the money.", time: "4d ago" },
      { id: 90, user: "mara.vinyl", text: "Wall-mounted shelf is genius. No more footstep vibration.", time: "4d ago" },
      { id: 91, user: "petra.spins", text: "Acoustic treatment makes such a difference. What panels did you go with?", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "4d ago",
    createdAt: now - 102 * hr,
    accent: "#84cc16",
  },
  {
    id: 2040,
    user: "kai.wax",
    type: "photo",
    caption: "Record Store Day haul from Rough Trade. Got there at 5am and it was worth every minute of lost sleep. The Radiohead reissue alone made the trip. #rsd #recordstoreday",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "OK Computer", artist: "Radiohead" },
    likes: 46,
    liked: false,
    comments: [
      { id: 92, user: "cleo.spins", text: "RSD is the best and worst day of the year for collectors", time: "5d ago" },
      { id: 93, user: "juniper.sounds", text: "What pressing? The OKNOTOK boxset?", time: "5d ago" },
      { id: 94, user: "kai.wax", text: "The blue vinyl repress. Sounds absolutely incredible.", time: "5d ago" },
    ],
    bookmarked: false,
    timeAgo: "5d ago",
    createdAt: now - 126 * hr,
    accent: "#a78bfa",
  },
  {
    id: 2041,
    user: "sol.spins",
    type: "question",
    caption: "Anyone here into Afrobeat? Been diving deep into the Fela Kuti catalog on vinyl. The 15-minute tracks are made for the LP format. This is where the music breathes. #afrobeat #felakuti",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Zombie", artist: "Fela Kuti" },
    likes: 33,
    liked: false,
    comments: [
      { id: 95, user: "zara.grooves", text: "Fela is essential. Zombie is the perfect entry point.", time: "2d ago" },
      { id: 96, user: "max.plays", text: "We just got a stack of Fela reissues at the shop. Come through!", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 60 * hr,
    accent: "#10b981",
  },
  {
    id: 2042,
    user: "tova.vinyl",
    type: "photo",
    caption: "My grandmother gave me her record collection today. Over 200 records from the 50s and 60s. Sinatra, Ella, Billie Holiday, Nina Simone. I'm not crying, you're crying. \uD83D\uDE22\u2764\uFE0F",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 87,
    liked: false,
    comments: [
      { id: 97, user: "lena.records", text: "That's incredibly special. What a gift. Treasure those.", time: "3d ago" },
      { id: 98, user: "mara.vinyl", text: "Original 50s jazz vocals on vinyl? That's a goldmine of warmth.", time: "3d ago" },
      { id: 99, user: "felix.rpm", text: "Nina Simone on original vinyl is something else entirely. You're lucky.", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 84 * hr,
    accent: "#ec4899",
  },
  {
    id: 2043,
    user: "creator",
    type: "photo",
    caption: "Sunday listening stack. Left to right: Coltrane, Mingus, Miles, Monk. Four pillars, four hours, four cups of coffee. This is what weekends are for. \u2615",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 72,
    liked: false,
    comments: [
      { id: 100, user: "mara.vinyl", text: "The perfect Sunday. Which Monk record?", time: "1d ago" },
      { id: 101, user: "creator", text: "Brilliant Corners. Always Brilliant Corners.", time: "1d ago" },
      { id: 102, user: "soren.stacks", text: "This is the way. No distractions, just music.", time: "22h ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 45 * hr,
    accent: "#0ea5e9",
  },
  {
    id: 2044,
    user: "wren.stacks",
    type: "review",
    caption: "PSA: if you're sleeping on Khruangbin you are missing out. Their live recordings on vinyl are some of the best pressing I've heard in years. The low end is unreal.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Con Todo El Mundo", artist: "Khruangbin" },
    likes: 39,
    liked: false,
    comments: [
      { id: 103, user: "felix.rpm", text: "Maria Tambien is the song of the decade. So groovy.", time: "4d ago" },
      { id: 104, user: "dax.wax", text: "Everything they touch is gold. The pressing quality is chef's kiss.", time: "4d ago" },
    ],
    bookmarked: false,
    timeAgo: "4d ago",
    createdAt: now - 108 * hr,
    accent: "#06b6d4",
  },
  {
    id: 2045,
    user: "thomas.wax",
    type: "photo",
    caption: "Dusted off the old Technics SL-1200 today. Twenty years old and still runs like a dream. They really don't build them like they used to. First spin: side A of Who's Next.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Who's Next", artist: "The Who" },
    likes: 44,
    liked: false,
    comments: [
      { id: 105, user: "bjorn.grooves", text: "SL-1200 is bulletproof. Mine is from 1998 and hasn't skipped a beat.", time: "5d ago" },
      { id: 106, user: "nadia.rpm", text: "Baba O'Riley on a 1200... that's how it was meant to be heard.", time: "5d ago" },
    ],
    bookmarked: false,
    timeAgo: "5d ago",
    createdAt: now - 132 * hr,
    accent: "#a78bfa",
  },
  // ── New posts ────────────────────────────────────────────────────────────────
  {
    id: 2046,
    user: "hal.grooves",
    type: "review",
    caption: "Played this front to back three times today. Robert Johnson recorded these songs in a hotel room in 1936 and they still sound like they're from another dimension. The Delta blues is timeless.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "King of the Delta Blues Singers", artist: "Robert Johnson" },
    likes: 25,
    liked: false,
    comments: [
      { id: 107, user: "thomas.wax", text: "The legend of the crossroads starts here. Essential listening.", time: "2d ago" },
      { id: 108, user: "dax.wax", text: "Picked up a reissue last month. The remastering is excellent.", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 63 * hr,
    accent: "#ef4444",
  },
  {
    id: 2047,
    user: "june.vinyl",
    type: "review",
    caption: "Voodoo on vinyl is a whole different experience. The warmth of D'Angelo's voice through analog just wraps around you. This album redefined what R&B could be. #neosoul #dangelo",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Voodoo", artist: "D'Angelo" },
    likes: 42,
    liked: false,
    comments: [
      { id: 109, user: "lena.records", text: "Untitled (How Does It Feel) on vinyl at night... transcendent.", time: "1d ago" },
      { id: 110, user: "ada.tracks", text: "The Soulquarians sessions were magic. This album is the proof.", time: "1d ago" },
      { id: 111, user: "nadia.rpm", text: "Questlove's drums on this record are so perfectly imperfect.", time: "20h ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 33 * hr,
    accent: "#06b6d4",
  },
  {
    id: 2048,
    user: "arlo.wax",
    type: "review",
    caption: "If you ever wonder why people go crazy for Townes Van Zandt, put on Waiting Around to Die at full volume in an empty room. That's all the explanation you'll ever need. #outlaw #americana",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Townes Van Zandt", artist: "Townes Van Zandt" },
    likes: 19,
    liked: false,
    comments: [
      { id: 112, user: "milo.vinyl", text: "Townes is the songwriter's songwriter. Nobody cuts deeper.", time: "3d ago" },
      { id: 113, user: "hal.grooves", text: "The blues and country connection is so clear in his work. Love it.", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 87 * hr,
    accent: "#f97316",
  },
  {
    id: 2049,
    user: "romy.rpm",
    type: "review",
    caption: "Violator is the perfect synth-pop album. Every single track is flawless. The production on Personal Jesus is still ahead of its time 35 years later. \uD83D\uDD79\uFE0F #depchemode #synthpop",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Violator", artist: "Depeche Mode" },
    likes: 36,
    liked: false,
    comments: [
      { id: 114, user: "otto.wax", text: "Enjoy the Silence on vinyl is peak new wave. Absolutely gorgeous.", time: "2d ago" },
      { id: 115, user: "beau.plays", text: "The bass on Policy of Truth shakes my apartment every time.", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 66 * hr,
    accent: "#8b5cf6",
  },
  {
    id: 2050,
    user: "emi.spins",
    type: "review",
    caption: "Music for 18 Musicians by Steve Reich. Sixty-seven minutes of pure hypnotic bliss. The way the patterns shift and interlock... you lose yourself completely. Best experienced on vinyl with no interruptions.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Music for 18 Musicians", artist: "Steve Reich" },
    likes: 16,
    liked: false,
    comments: [
      { id: 116, user: "petra.spins", text: "The original ECM pressing is sublime. Do you have that one?", time: "5d ago" },
      { id: 117, user: "soren.stacks", text: "Minimalism on vinyl is a contradiction that works perfectly.", time: "5d ago" },
    ],
    bookmarked: false,
    timeAgo: "5d ago",
    createdAt: now - 138 * hr,
    accent: "#0ea5e9",
  },
  {
    id: 2051,
    user: "vince.rpm",
    type: "photo",
    caption: "East LA swap meet haul. Thee Midniters, El Chicano, and a pristine copy of War's The World Is a Ghetto. Lowrider soul at its finest. The oldies are alive and well in the barrio. \uD83D\uDE97\uD83C\uDFB6",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "The World Is a Ghetto", artist: "War" },
    likes: 31,
    liked: false,
    comments: [
      { id: 118, user: "felix.rpm", text: "War is so underrated. The City Country City is one of the best instrumentals ever.", time: "1d ago" },
      { id: 119, user: "dax.wax", text: "Swap meets are goldmines. Great finds!", time: "1d ago" },
      { id: 120, user: "nico.crates", text: "That El Chicano record is incredible. Viva La Raza!", time: "22h ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 38 * hr,
    accent: "#ec4899",
  },
  {
    id: 2052,
    user: "freya.wax",
    type: "review",
    caption: "Jan Garbarek and the Hilliard Ensemble. Medieval vocal music meets Norwegian jazz saxophone. This should not work but it's one of the most beautiful records ever pressed. ECM at its finest.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Officium", artist: "Jan Garbarek & The Hilliard Ensemble" },
    likes: 14,
    liked: false,
    comments: [
      { id: 121, user: "soren.stacks", text: "ECM's catalog is a treasure trove. This one is special.", time: "4d ago" },
      { id: 122, user: "mara.vinyl", text: "The acoustics on this recording are otherworldly.", time: "4d ago" },
    ],
    bookmarked: false,
    timeAgo: "4d ago",
    createdAt: now - 114 * hr,
    accent: "#3b82f6",
  },
  {
    id: 2053,
    user: "dante.grooves",
    type: "review",
    caption: "Goblin's Suspiria soundtrack. Dario Argento knew exactly what he was doing pairing those visuals with this music. Progressive rock horror at its absolute peak. \uD83C\uDFB9\uD83D\uDC80",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Suspiria", artist: "Goblin" },
    likes: 23,
    liked: false,
    comments: [
      { id: 123, user: "riku.records", text: "Italian prog is so underrated. Goblin, PFM, Banco... legends.", time: "3d ago" },
      { id: 124, user: "bjorn.grooves", text: "This soundtrack is genuinely terrifying. In the best way.", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 90 * hr,
    accent: "#a78bfa",
  },
  {
    id: 2054,
    user: "priya.stacks",
    type: "announcement",
    caption: "Hello from Mumbai! Finally joining GrooveStack. Looking for other collectors who are into Bollywood soundtracks on vinyl, especially the golden age - RD Burman, Laxmikant-Pyarelal, SD Burman. The Indian pressings have incredible warmth. #bollywood #vinylcollector",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 22,
    liked: false,
    comments: [
      { id: 125, user: "sol.spins", text: "Welcome! I don't know much about Bollywood vinyl but I'd love to learn more.", time: "2d ago" },
      { id: 126, user: "yuki.vinyl", text: "Indian pressings are fascinating. What label should I look for?", time: "2d ago" },
      { id: 127, user: "priya.stacks", text: "HMV India (His Master's Voice) for the originals. Saregama for reissues.", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 69 * hr,
    accent: "#d946ef",
  },
  {
    id: 2055,
    user: "lou.vinyl",
    type: "review",
    caption: "Here Are the Sonics!!! is the blueprint for every garage band that came after. Recorded in 1965 and still heavier than 90% of what passes for rock today. Play it LOUD. #garagepunk #thesonics",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Here Are the Sonics!!!", artist: "The Sonics" },
    likes: 27,
    liked: false,
    comments: [
      { id: 128, user: "cass.stacks", text: "The Witch is one of the greatest proto-punk tracks ever. Absolutely feral.", time: "5d ago" },
      { id: 129, user: "wren.stacks", text: "These guys were punk before punk existed. Total legends.", time: "5d ago" },
    ],
    bookmarked: false,
    timeAgo: "5d ago",
    createdAt: now - 144 * hr,
    accent: "#f97316",
  },
  {
    id: 2056,
    user: "maya.tracks",
    type: "review",
    caption: "Alice Coltrane's Journey in Satchidananda. Spiritual jazz at its most transcendent. The harp, the bass, Pharoah Sanders' soprano sax... this album is a meditation. Put it on and let go. \uD83D\uDE4F",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Journey in Satchidananda", artist: "Alice Coltrane" },
    likes: 35,
    liked: false,
    comments: [
      { id: 130, user: "mara.vinyl", text: "Alice Coltrane deserves so much more recognition. This is a masterpiece.", time: "1d ago" },
      { id: 131, user: "felix.rpm", text: "The harp on this record is unlike anything else in jazz. Pure beauty.", time: "1d ago" },
      { id: 132, user: "tova.vinyl", text: "I play this when I need the world to slow down. It always works.", time: "22h ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 40 * hr,
    accent: "#14b8a6",
  },
  {
    id: 2057,
    user: "liam.stacks",
    type: "review",
    caption: "The Drive soundtrack on vinyl. Nightcall playing as the sun goes down is a whole experience. Cliff Martinez understood the assignment. Synthwave before synthwave was a thing. #synthwave #drive",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Drive OST", artist: "Cliff Martinez" },
    likes: 32,
    liked: false,
    comments: [
      { id: 133, user: "beau.plays", text: "Kavinsky's Nightcall is the most atmospheric opening to any film. Period.", time: "3d ago" },
      { id: 134, user: "romy.rpm", text: "This soundtrack basically launched an entire genre aesthetic.", time: "3d ago" },
      { id: 135, user: "juniper.sounds", text: "Under Your Spell by Desire is criminally underrated from this OST.", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 93 * hr,
    accent: "#8b5cf6",
  },
  {
    id: 2058,
    user: "theo.plays",
    type: "review",
    caption: "Chuck Brown invented go-go music and DC has never been the same. Bustin' Loose is the song that plays in every backyard cookout, every block party, every celebration. Put some respect on his name. #gogo #dc #chuckbrown",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Bustin' Loose", artist: "Chuck Brown & The Soul Searchers" },
    likes: 28,
    liked: false,
    comments: [
      { id: 136, user: "max.plays", text: "Go-go is one of the most important regional genres in America. Respect.", time: "2d ago" },
      { id: 137, user: "nadia.rpm", text: "DC's contribution to Black music is massive. Chuck Brown is a legend.", time: "2d ago" },
      { id: 138, user: "dax.wax", text: "Found this on original pressing at a DC flea market years ago. Treasure it.", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 72 * hr,
    accent: "#06b6d4",
  },
  {
    id: 2059,
    user: "nina.grooves",
    type: "announcement",
    caption: "Greetings from Belgrade! Bringing some Balkan flavor to GrooveStack. If anyone's interested in Yugo-rock, turbo-folk, or Balkan brass on vinyl, I'm your person. The pressing plants in Yugoslavia made surprisingly good vinyl. #yugorock #balkan",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 15,
    liked: false,
    comments: [
      { id: 139, user: "dante.grooves", text: "Yugo-rock is incredible. Bijelo Dugme is like the Balkan Led Zeppelin.", time: "4d ago" },
      { id: 140, user: "otto.wax", text: "Eastern European vinyl is a whole unexplored world. Welcome!", time: "4d ago" },
    ],
    bookmarked: false,
    timeAgo: "4d ago",
    createdAt: now - 120 * hr,
    accent: "#ca8a04",
  },
  {
    id: 2060,
    user: "finn.crates",
    type: "review",
    caption: "The Chieftains playing traditional Irish music on vinyl. There's a warmth to these recordings that digital just can't capture. The uillean pipes sound like they're in the room with you. Slainte! \uD83C\uDF40",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "The Chieftains 4", artist: "The Chieftains" },
    likes: 12,
    liked: false,
    comments: [
      { id: 141, user: "cass.stacks", text: "Fellow Irish vinyl head! The trad scene on wax is so underrated.", time: "6d ago" },
      { id: 142, user: "milo.vinyl", text: "Celtic folk and Americana share so much DNA. Love this.", time: "6d ago" },
    ],
    bookmarked: false,
    timeAgo: "6d ago",
    createdAt: now - 156 * hr,
    accent: "#22c55e",
  },
  {
    id: 2061,
    user: "creator",
    type: "question",
    caption: "Settling a debate: mono vs. stereo pressings - which do you prefer for 60s jazz? I've been A/B testing my Kind of Blue copies and honestly the mono wins every time for me. The instruments feel more cohesive. #mono #stereo #vinyl",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Kind of Blue", artist: "Miles Davis" },
    likes: 67,
    liked: false,
    comments: [
      { id: 143, user: "mara.vinyl", text: "Mono for jazz, stereo for rock. That's my rule and I'm sticking to it.", time: "8h ago" },
      { id: 144, user: "thomas.wax", text: "Stereo on early 60s records was an afterthought. Mono is the intended mix.", time: "7h ago" },
      { id: 145, user: "soren.stacks", text: "Depends on the mastering engineer. Some stereo mixes are incredible.", time: "6h ago" },
      { id: 146, user: "tova.vinyl", text: "My grandmother's mono jazz records sound better than any reissue I own.", time: "5h ago" },
    ],
    bookmarked: false,
    timeAgo: "10h ago",
    createdAt: now - 10 * hr,
    accent: "#0ea5e9",
  },
  {
    id: 2062,
    user: "max.plays",
    type: "trade",
    caption: "Shop update: just got in a collection of 200+ funk and soul 45s. Northern soul, deep funk, rare grooves. Some serious heat in here. Come dig this weekend or DM me for wants. #recordstore #raresoul #45s",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 53,
    liked: false,
    comments: [
      { id: 147, user: "dax.wax", text: "I'll be there Saturday at opening. Save me nothing, I want the hunt.", time: "1d ago" },
      { id: 148, user: "lena.records", text: "Any Atlantic or Stax singles in there?", time: "1d ago" },
      { id: 149, user: "max.plays", text: "Multiple Stax, some King, and a few Motown promos. Come early.", time: "22h ago" },
      { id: 150, user: "theo.plays", text: "Any go-go or DC funk 45s? I need some Trouble Funk.", time: "20h ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 27 * hr,
    accent: "#a78bfa",
  },
  {
    id: 2063,
    user: "cleo.spins",
    type: "trade",
    caption: "Thinning my collection: letting go of some 90s indie duplicates. Pavement, Guided by Voices, Sebadoh, and a few Matador singles. All VG+ or better. DM if interested. #forsale #90sindie",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 22,
    liked: false,
    comments: [
      { id: 151, user: "kai.wax", text: "What Pavement records? I need Slanted and Enchanted on vinyl.", time: "3d ago" },
      { id: 152, user: "wren.stacks", text: "GBV? Which era? Alien Lanes is my white whale.", time: "3d ago" },
      { id: 153, user: "cleo.spins", text: "Both available! DM me for prices. First come first served.", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 96 * hr,
    accent: "#84cc16",
  },
  {
    id: 2064,
    user: "nadia.rpm",
    type: "review",
    caption: "To Pimp a Butterfly is the most ambitious hip-hop album ever made. Period. The jazz, the funk, the poetry, the politics. Kendrick made a record that will be studied for decades. Every spin reveals something new. \uD83E\uDD4B",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "To Pimp a Butterfly", artist: "Kendrick Lamar" },
    likes: 71,
    liked: false,
    comments: [
      { id: 154, user: "felix.rpm", text: "The jazz musicianship on this record is incredible. Thundercat, Kamasi, Terrace Martin...", time: "12h ago" },
      { id: 155, user: "june.vinyl", text: "Wesley's Theory is one of the best opening tracks of all time.", time: "11h ago" },
      { id: 156, user: "max.plays", text: "This is what happens when hip-hop and jazz collide perfectly.", time: "10h ago" },
    ],
    bookmarked: false,
    timeAgo: "14h ago",
    createdAt: now - 14 * hr,
    accent: "#8b5cf6",
  },
  {
    id: 2065,
    user: "thomas.wax",
    type: "question",
    caption: "What's everyone's turntable setup? I'm running a Technics SL-1200 MK2 into a Cambridge Audio Alva Duo into a Yamaha A-S801. Speakers are JBL L100 Classics. Been thinking about upgrading the cart. Suggestions? #setup #turntable #hifi",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 38,
    liked: false,
    comments: [
      { id: 157, user: "ada.tracks", text: "That's a solid chain. For carts, look at the Nagaoka MP-200. Punches way above its price.", time: "1w ago" },
      { id: 158, user: "bjorn.grooves", text: "Ortofon 2M Bronze. Changed my life. Worth every penny.", time: "1w ago" },
      { id: 159, user: "mara.vinyl", text: "Audio-Technica AT-VM95ML. Micro-line stylus for detailed tracking.", time: "6d ago" },
    ],
    bookmarked: false,
    timeAgo: "1w ago",
    createdAt: now - 7 * day,
    accent: "#a78bfa",
  },
  {
    id: 2066,
    user: "sol.spins",
    type: "review",
    caption: "Tony Allen is the greatest drummer who ever lived. Full stop. His work with Fela created the rhythmic foundation of Afrobeat. Listen to those polyrhythms on vinyl and try not to move. Impossible. #tonyallen #afrobeat",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Expensive Shit", artist: "Fela Kuti" },
    likes: 24,
    liked: false,
    comments: [
      { id: 160, user: "zara.grooves", text: "Tony Allen's feel is completely unique. Nobody can replicate it.", time: "5d ago" },
      { id: 161, user: "max.plays", text: "The rhythm section on Fela's records is tighter than any band in history.", time: "5d ago" },
    ],
    bookmarked: false,
    timeAgo: "5d ago",
    createdAt: now - 150 * hr,
    accent: "#10b981",
  },
  {
    id: 2067,
    user: "ada.tracks",
    type: "question",
    caption: "Room acoustics question for the timeline: has anyone tried DIY bass traps? My room has a nasty 80Hz resonance that's muddying up everything below 200Hz. Thinking about building some rockwool panel traps for the corners. #acoustics #hifi #diy",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 18,
    liked: false,
    comments: [
      { id: 162, user: "thomas.wax", text: "Rockwool in wooden frames with fabric covering. Cheap and effective. Did it last year.", time: "2w ago" },
      { id: 163, user: "petra.spins", text: "GIK Acoustics makes excellent pre-built traps if you don't want to DIY.", time: "2w ago" },
    ],
    bookmarked: false,
    timeAgo: "2w ago",
    createdAt: now - 14 * day,
    accent: "#84cc16",
  },
  {
    id: 2068,
    user: "lena.records",
    type: "review",
    caption: "Otis Redding at Monterey Pop. Live on vinyl. The crowd didn't know what hit them. Try a Little Tenderness builds to one of the most explosive endings in music history. RIP Otis. #soul #otisredding #monterey",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Live in Europe", artist: "Otis Redding" },
    likes: 37,
    liked: false,
    comments: [
      { id: 164, user: "june.vinyl", text: "The greatest live performer in soul history. Nobody came close.", time: "1w ago" },
      { id: 165, user: "max.plays", text: "Dock of the Bay was recorded 3 days before he died. Unfinished perfection.", time: "1w ago" },
    ],
    bookmarked: false,
    timeAgo: "1w ago",
    createdAt: now - 8 * day,
    accent: "#ec4899",
  },
  {
    id: 2069,
    user: "wren.stacks",
    type: "review",
    caption: "King Gizzard dropped ANOTHER album and somehow it's great again. These guys are the most prolific band of the 2020s. Already on my third spin. The microtonal stuff is wild on vinyl. \uD83E\uDD8E #kinggizzard #psychrock",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Nonagon Infinity", artist: "King Gizzard & The Lizard Wizard" },
    likes: 29,
    liked: false,
    comments: [
      { id: 166, user: "kai.wax", text: "The seamless loop on Nonagon Infinity is genius. Robot Stop into Big Fig Wasp forever.", time: "4d ago" },
      { id: 167, user: "cleo.spins", text: "Their colored vinyl variants are insane. My shelf looks like a rainbow.", time: "4d ago" },
    ],
    bookmarked: false,
    timeAgo: "4d ago",
    createdAt: now - 111 * hr,
    accent: "#84cc16",
  },
  {
    id: 2070,
    user: "creator",
    type: "announcement",
    caption: "Milestone alert: just completed my Blue Note 1500 series collection. Every single record from BLP 1501 to BLP 1599. Took me 8 years of hunting. Most emotional was finding the original Art Blakey Moanin' pressing. This hobby is wild. \uD83C\uDFC6",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 112,
    liked: false,
    comments: [
      { id: 168, user: "mara.vinyl", text: "This is one of the most impressive collecting achievements I've ever seen. Massive congrats!", time: "3h ago" },
      { id: 169, user: "max.plays", text: "As a shop owner, I know how hard some of those are to find. Incredible dedication.", time: "2h ago" },
      { id: 170, user: "yuki.vinyl", text: "The 1500 series is the golden age of jazz on vinyl. What an accomplishment.", time: "2h ago" },
      { id: 171, user: "tova.vinyl", text: "Which one was the hardest to find?", time: "1h ago" },
      { id: 172, user: "creator", text: "Sonny Clark's Cool Struttin'. Took 3 years and cost me dearly. Worth it.", time: "45m ago" },
    ],
    bookmarked: false,
    timeAgo: "4h ago",
    createdAt: now - 4 * hr,
    accent: "#0ea5e9",
  },
  // ── Poll-type posts ─────────────────────────────────────────────────────────
  {
    id: 2071,
    user: "nadia.rpm",
    type: "poll",
    caption: "Settling this once and for all. Greatest hip-hop album of the 90s?",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    pollOptions: [
      { id: "p1a", text: "Illmatic - Nas", votes: 187 },
      { id: "p1b", text: "Ready to Die - Notorious B.I.G.", votes: 142 },
      { id: "p1c", text: "Enter the Wu-Tang - Wu-Tang Clan", votes: 98 },
      { id: "p1d", text: "Aquemini - OutKast", votes: 73 },
    ],
    pollEndsAt: now + 2 * day,
    likes: 89,
    liked: false,
    comments: [
      { id: 173, user: "dax.wax", text: "Illmatic and it's not even close. Perfect from front to back.", time: "6h ago" },
      { id: 174, user: "june.vinyl", text: "Aquemini is slept on in this poll. ATLiens too.", time: "5h ago" },
      { id: 175, user: "theo.plays", text: "The Infamous by Mobb Deep needs to be on here!", time: "4h ago" },
    ],
    bookmarked: false,
    timeAgo: "8h ago",
    createdAt: now - 8 * hr,
    accent: "#8b5cf6",
  },
  {
    id: 2072,
    user: "thomas.wax",
    type: "poll",
    caption: "Turntable debate: belt drive or direct drive? I've owned both and I keep going back to direct drive. What's your preference?",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    pollOptions: [
      { id: "p2a", text: "Direct Drive (Technics, etc.)", votes: 234 },
      { id: "p2b", text: "Belt Drive (Rega, Pro-Ject, etc.)", votes: 198 },
      { id: "p2c", text: "Idler Drive (Garrard, Thorens, etc.)", votes: 31 },
      { id: "p2d", text: "Doesn't matter, it's all about the cartridge", votes: 67 },
    ],
    pollEndsAt: now + 3 * day,
    likes: 52,
    liked: false,
    comments: [
      { id: 176, user: "ada.tracks", text: "Direct drive for speed stability. Belt drive for isolation. Both have merits.", time: "1d ago" },
      { id: 177, user: "bjorn.grooves", text: "My SL-1200 has survived 20 years of abuse. Direct drive forever.", time: "1d ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 30 * hr,
    accent: "#a78bfa",
  },
  {
    id: 2073,
    user: "cleo.spins",
    type: "poll",
    caption: "How do you organize your record collection? I've been alphabetical forever but I'm tempted to switch to genre-first.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    pollOptions: [
      { id: "p3a", text: "Alphabetical by artist", votes: 312 },
      { id: "p3b", text: "By genre, then alphabetical", votes: 189 },
      { id: "p3c", text: "By label", votes: 45 },
      { id: "p3d", text: "Chronological by year", votes: 28 },
      { id: "p3e", text: "Autobiographical (High Fidelity style)", votes: 56 },
    ],
    pollEndsAt: now + 1 * day,
    likes: 67,
    liked: false,
    comments: [
      { id: 178, user: "juniper.sounds", text: "I organize by BPM and I'm not sorry about it.", time: "2d ago" },
      { id: 179, user: "mara.vinyl", text: "By label for jazz. Alphabetical for everything else.", time: "2d ago" },
      { id: 180, user: "otto.wax", text: "Autobiographical is the only correct answer.", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 56 * hr,
    accent: "#84cc16",
  },
  {
    id: 2074,
    user: "felix.rpm",
    type: "poll",
    caption: "Controversial question: does colored vinyl actually sound worse than standard black vinyl? I've had mixed experiences.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    pollOptions: [
      { id: "p4a", text: "Yes, black vinyl always sounds better", votes: 145 },
      { id: "p4b", text: "No difference with modern pressing quality", votes: 201 },
      { id: "p4c", text: "Depends on the pressing plant", votes: 178 },
      { id: "p4d", text: "Picture discs are worse, colored vinyl is fine", votes: 89 },
    ],
    pollEndsAt: now + 4 * day,
    likes: 41,
    liked: false,
    comments: [
      { id: 181, user: "ada.tracks", text: "Technically the carbon in black vinyl provides better groove consistency. In practice, most people can't tell.", time: "3d ago" },
      { id: 182, user: "wren.stacks", text: "My King Gizzard colored pressings sound great. It's about the plant, not the color.", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 80 * hr,
    accent: "#06b6d4",
  },
  // ── Event-type posts ────────────────────────────────────────────────────────
  {
    id: 2075,
    user: "max.plays",
    type: "event",
    caption: "SHOP EVENT: Funk & Soul Saturday at Groove City Records! Live DJ spinning rare 45s, 20% off all funk/soul vinyl, and free coffee. Bring your want lists!",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    eventDetails: { name: "Funk & Soul Saturday", location: "Groove City Records, Chicago, IL", date: new Date(now + 3 * day).toISOString(), time: "11:00 AM - 6:00 PM", rsvpCount: 47 },
    likes: 63,
    liked: false,
    comments: [
      { id: 183, user: "dax.wax", text: "I'll be there at 11 sharp. Save me a parking spot.", time: "12h ago" },
      { id: 184, user: "lena.records", text: "Flying in from Frankfurt for this. Kidding. But I wish I could.", time: "11h ago" },
      { id: 185, user: "theo.plays", text: "Any go-go in the funk section? I'm making the drive from DC.", time: "10h ago" },
    ],
    bookmarked: false,
    timeAgo: "14h ago",
    createdAt: now - 14 * hr,
    accent: "#a78bfa",
  },
  {
    id: 2076,
    user: "juniper.sounds",
    type: "event",
    caption: "LISTENING PARTY: Ambient & Electronic evening at my flat. Bringing out the rare Warp pressings, the KEF speakers, and some nice wine. Limited to 8 people. DM for address.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    eventDetails: { name: "Ambient Listening Party", location: "East London, UK", date: new Date(now + 5 * day).toISOString(), time: "7:00 PM - Late", rsvpCount: 6 },
    likes: 34,
    liked: false,
    comments: [
      { id: 186, user: "beau.plays", text: "Can I bring my Boards of Canada collection? I'll also bring wine.", time: "1d ago" },
      { id: 187, user: "soren.stacks", text: "Wish I could make it from Copenhagen. Next time I'm in London!", time: "1d ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 28 * hr,
    accent: "#f97316",
  },
  {
    id: 2077,
    user: "cass.stacks",
    type: "event",
    caption: "DUBLIN VINYL SWAP: Monthly record swap at The Workman's Club. Bring records you want to trade, cash for buying, and good vibes. All genres welcome but punk gets priority seating.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    eventDetails: { name: "Dublin Monthly Vinyl Swap", location: "The Workman's Club, Dublin, IE", date: new Date(now + 7 * day).toISOString(), time: "2:00 PM - 7:00 PM", rsvpCount: 32 },
    likes: 28,
    liked: false,
    comments: [
      { id: 188, user: "finn.crates", text: "I'll have a stack of trad Irish and some punk duplicates. See you there!", time: "2d ago" },
      { id: 189, user: "otto.wax", text: "Might take the ferry over. Any post-punk traders usually show up?", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 54 * hr,
    accent: "#0ea5e9",
  },
  {
    id: 2078,
    user: "yuki.vinyl",
    type: "event",
    caption: "TOKYO RECORD FAIR: Annual Shibuya record fair is next weekend! Over 100 dealers from across Japan. The J-jazz and city pop sections are always incredible. Who's going?",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    eventDetails: { name: "Shibuya Record Fair", location: "Shibuya Hikarie, Tokyo, JP", date: new Date(now + 10 * day).toISOString(), time: "10:00 AM - 8:00 PM", rsvpCount: 89 },
    likes: 51,
    liked: false,
    comments: [
      { id: 190, user: "mara.vinyl", text: "I'm planning a Japan trip around this! What should I budget for J-jazz originals?", time: "1d ago" },
      { id: 191, user: "yuki.vinyl", text: "Bring at least $500 if you're serious about originals. Some rare pressings go fast.", time: "22h ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 36 * hr,
    accent: "#f59e0b",
  },
  // ── Trade-request posts ─────────────────────────────────────────────────────
  {
    id: 2079,
    user: "riku.records",
    type: "trade_request",
    caption: "TRADE: Looking to swap my NM copy of Opeth - Damnation for a clean copy of Porcupine Tree - In Absentia. Willing to add cash if needed. DM me!",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Damnation", artist: "Opeth" },
    tradeDetails: { offering: { album: "Damnation", artist: "Opeth", condition: "NM" }, seeking: { album: "In Absentia", artist: "Porcupine Tree", condition: "VG+" }, willingToAddCash: true },
    likes: 16,
    liked: false,
    comments: [
      { id: 192, user: "bjorn.grooves", text: "I have a VG+ In Absentia. DM sent!", time: "1d ago" },
      { id: 193, user: "iris.rpm", text: "Great trade offer. Damnation is such a beautiful album.", time: "1d ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 32 * hr,
    accent: "#8b5cf6",
  },
  {
    id: 2080,
    user: "otto.wax",
    type: "trade_request",
    caption: "TRADE: Have duplicates of Joy Division - Closer (2007 remaster, NM) and Siouxsie - Juju (VG+). Looking for Bauhaus - In the Flat Field or anything Killing Joke on original pressing.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Closer", artist: "Joy Division" },
    tradeDetails: { offering: { album: "Closer / Juju", artist: "Joy Division / Siouxsie", condition: "NM / VG+" }, seeking: { album: "In the Flat Field / any Killing Joke", artist: "Bauhaus / Killing Joke", condition: "VG+" }, willingToAddCash: false },
    likes: 21,
    liked: false,
    comments: [
      { id: 194, user: "cass.stacks", text: "I might have a Killing Joke self-titled. Let me check the condition.", time: "3d ago" },
      { id: 195, user: "cleo.spins", text: "That Juju is tempting... I don't have any Bauhaus to trade though.", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 82 * hr,
    accent: "#ef4444",
  },
  {
    id: 2081,
    user: "nico.crates",
    type: "trade_request",
    caption: "TRADE: Offering my NM Getz/Gilberto (reissue) for any original pressing of Caetano Veloso or Gilberto Gil from the tropicalia era. Also looking for Os Mutantes. Will trade 2-for-1 for originals!",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Getz/Gilberto", artist: "Stan Getz & Joao Gilberto" },
    tradeDetails: { offering: { album: "Getz/Gilberto", artist: "Stan Getz & Joao Gilberto", condition: "NM" }, seeking: { album: "Any tropicalia original", artist: "Caetano Veloso / Gilberto Gil / Os Mutantes", condition: "VG" }, willingToAddCash: true },
    likes: 14,
    liked: false,
    comments: [
      { id: 196, user: "felix.rpm", text: "I have a Brazilian pressing of Gilberto Gil's Refazenda. Interested?", time: "2d ago" },
      { id: 197, user: "mateo.spins", text: "Check the Latin shops in East LA. I've seen tropicalia originals there.", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 62 * hr,
    accent: "#f97316",
  },
  {
    id: 2082,
    user: "milo.vinyl",
    type: "trade_request",
    caption: "TRADE: Have a VG+ copy of Joni Mitchell - Blue that I picked up as a duplicate. Looking for any Nick Drake or Vashti Bunyan on vinyl. Happy to work out a fair deal. #folkvinyl #trade",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Blue", artist: "Joni Mitchell" },
    tradeDetails: { offering: { album: "Blue", artist: "Joni Mitchell", condition: "VG+" }, seeking: { album: "Any title", artist: "Nick Drake / Vashti Bunyan", condition: "VG" }, willingToAddCash: true },
    likes: 23,
    liked: false,
    comments: [
      { id: 198, user: "arlo.wax", text: "Joni's Blue for Nick Drake? That's a beautiful trade either way.", time: "4d ago" },
      { id: 199, user: "cleo.spins", text: "Vashti Bunyan originals are so rare. Good luck!", time: "4d ago" },
    ],
    bookmarked: false,
    timeAgo: "4d ago",
    createdAt: now - 105 * hr,
    accent: "#84cc16",
  },
  // ── Milestone celebration posts ─────────────────────────────────────────────
  {
    id: 2083,
    user: "mara.vinyl",
    type: "milestone",
    caption: "Just hit 500 records in my collection! Started 4 years ago with a single Coltrane record and now I need another shelf. Every single one has a story. Here's to 500 more. \uD83C\uDF89",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    milestoneDetails: { type: "collection_size", value: 500, previousMilestone: 250 },
    likes: 76,
    liked: false,
    comments: [
      { id: 200, user: "felix.rpm", text: "500 club! The first 100 felt slow, the next 400 fly by.", time: "6h ago" },
      { id: 201, user: "yuki.vinyl", text: "What percentage is jazz? I'm guessing at least 60%.", time: "5h ago" },
      { id: 202, user: "mara.vinyl", text: "73% jazz actually. I have a problem and I love it.", time: "4h ago" },
    ],
    bookmarked: false,
    timeAgo: "8h ago",
    createdAt: now - 8 * hr,
    accent: "#ec4899",
  },
  {
    id: 2084,
    user: "dax.wax",
    type: "milestone",
    caption: "1000 RECORDS. One thousand. My partner says it's too many. I say it's not enough. Started with dollar bin digs and now I've got a room dedicated to the collection. No regrets. #1kclub",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    milestoneDetails: { type: "collection_size", value: 1000, previousMilestone: 500 },
    likes: 94,
    liked: false,
    comments: [
      { id: 203, user: "max.plays", text: "Welcome to the 1K club! My shop doesn't count, but my personal collection just crossed 1000 too.", time: "2d ago" },
      { id: 204, user: "nadia.rpm", text: "A whole room?! Goals. What does the setup look like?", time: "2d ago" },
      { id: 205, user: "dax.wax", text: "Kallax shelves on three walls, turntable in the center, and a reading chair. Paradise.", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 58 * hr,
    accent: "#06b6d4",
  },
  {
    id: 2085,
    user: "beau.plays",
    type: "milestone",
    caption: "100 consecutive days of vinyl listening! Haven't missed a single day since I started tracking with Vinyl Buddy. Some days it's a full album session, some days it's one side of a 12-inch. But the streak lives! \uD83D\uDD25",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    milestoneDetails: { type: "listening_streak", value: 100, previousMilestone: 30 },
    likes: 58,
    liked: false,
    comments: [
      { id: 206, user: "juniper.sounds", text: "100 days! That's dedication. My best streak is 47.", time: "1d ago" },
      { id: 207, user: "soren.stacks", text: "The daily ritual of putting a needle on wax. Nothing better.", time: "1d ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 34 * hr,
    accent: "#f59e0b",
  },
  {
    id: 2086,
    user: "max.plays",
    type: "milestone",
    caption: "Groove City Records turns 5 years old today! From a tiny booth at a flea market to a full shop with 10,000+ records. Thank you to this community for the support. Free coffee and 10% off everything today! \uD83C\uDF82",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    milestoneDetails: { type: "anniversary", value: 5, unit: "years" },
    likes: 131,
    liked: false,
    comments: [
      { id: 208, user: "dax.wax", text: "Happy birthday Groove City! Best shop in Chicago, hands down.", time: "3h ago" },
      { id: 209, user: "lena.records", text: "Congratulations Max! 5 years of keeping the culture alive.", time: "2h ago" },
      { id: 210, user: "nadia.rpm", text: "Need to make a pilgrimage to Chicago just for this shop.", time: "2h ago" },
      { id: 211, user: "creator", text: "Congrats Max! My Kind of Blue came from your shop. You changed my life.", time: "1h ago" },
    ],
    bookmarked: false,
    timeAgo: "4h ago",
    createdAt: now - 4 * hr,
    accent: "#a78bfa",
  },
  {
    id: 2087,
    user: "sol.spins",
    type: "milestone",
    caption: "First sale on GrooveStack! Sold a Fela Kuti reissue to a collector in Brooklyn. The marketplace works! Shoutout to the community for making this easy. More listings coming soon. \uD83C\uDF1F",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    milestoneDetails: { type: "first_sale", value: 1, previousMilestone: 0 },
    likes: 29,
    liked: false,
    comments: [
      { id: 212, user: "zara.grooves", text: "Congrats on the first sale! The marketplace is great for finding collectors who actually appreciate what you're selling.", time: "5d ago" },
      { id: 213, user: "nadia.rpm", text: "Welcome to the seller side! It's addictive.", time: "5d ago" },
    ],
    bookmarked: false,
    timeAgo: "5d ago",
    createdAt: now - 130 * hr,
    accent: "#10b981",
  },
  // ── Additional posts to reach 90 ────────────────────────────────────────────
  {
    id: 2088,
    user: "astrid.vinyl",
    type: "review",
    caption: "Heaven or Las Vegas is the most perfect album the Cocteau Twins ever made. Liz Fraser's voice on vinyl is otherworldly. The reverb, the shimmer, the emotion. 4AD at its finest. #cocteautwins #dreampop",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Heaven or Las Vegas", artist: "Cocteau Twins" },
    likes: 33,
    liked: false,
    comments: [
      { id: 214, user: "cleo.spins", text: "The most beautiful album ever made. I will die on this hill.", time: "1d ago" },
      { id: 215, user: "otto.wax", text: "4AD pressings from this era are gorgeous. The artwork alone is worth it.", time: "1d ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 42 * hr,
    accent: "#a855f7",
  },
  {
    id: 2089,
    user: "omar.beats",
    type: "review",
    caption: "Egyptian jazz-funk from the 70s is the most slept-on genre in the world. This pressing from Cairo sounds incredible. The grooves are deep and the rhythm section is untouchable. #middleeasternvinyl",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Jazz, Jazz, Jazz", artist: "The Three Pyramids" },
    likes: 18,
    liked: false,
    comments: [
      { id: 216, user: "sol.spins", text: "Middle Eastern grooves on vinyl! I need to explore this more.", time: "3d ago" },
      { id: 217, user: "felix.rpm", text: "The global funk scene is so much deeper than people realize.", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 85 * hr,
    accent: "#f59e0b",
  },
  {
    id: 2090,
    user: "rosie.wax",
    type: "review",
    caption: "Krzysztof Komeda's Astigmatic is the greatest Polish jazz album ever recorded. The Muza pressing has this warmth that modern reissues can't touch. Eastern European jazz on vinyl is a whole world waiting to be discovered.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Astigmatic", artist: "Krzysztof Komeda" },
    likes: 15,
    liked: false,
    comments: [
      { id: 218, user: "freya.wax", text: "Polish jazz is incredible. Tomasz Stanko, Zbigniew Namyslowski... so much to explore.", time: "4d ago" },
      { id: 219, user: "mara.vinyl", text: "Adding this to my want list. Eastern European jazz is my next rabbit hole.", time: "4d ago" },
    ],
    bookmarked: false,
    timeAgo: "4d ago",
    createdAt: now - 108 * hr,
    accent: "#ec4899",
  },
  {
    id: 2091,
    user: "hal.grooves",
    type: "review",
    caption: "Robert Johnson recorded 29 songs in two sessions in 1936 and 1937. Those 29 songs created the blueprint for everything we call blues, rock, and roll. This Columbia pressing of King of the Delta Blues Singers is my most treasured possession.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "King of the Delta Blues Singers", artist: "Robert Johnson" },
    likes: 28,
    liked: false,
    comments: [
      { id: 220, user: "lena.records", text: "The mythology around Robert Johnson is incredible but the music speaks for itself.", time: "5h ago" },
      { id: 221, user: "dax.wax", text: "Cross Road Blues on vinyl hits different. You can hear the room.", time: "4h ago" },
    ],
    bookmarked: false,
    timeAgo: "5d ago",
    createdAt: now - 120 * hr,
    accent: "#2563eb",
    reactions: { fire: 10, heart: 14, vinyl: 6 },
    views: 194,
  },
  {
    id: 2092,
    user: "petra.spins",
    type: "review",
    caption: "Glenn Gould recorded the Goldberg Variations twice. The 1955 version is youthful, brash, and revolutionary. The 1981 version is contemplative and profound. Both are essential. This is the 1955 Columbia Masterworks pressing.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Goldberg Variations", artist: "Glenn Gould" },
    likes: 22,
    liked: false,
    comments: [
      { id: 222, user: "emi.spins", text: "The 1955 recording changed how people thought about Bach. Gould was only 22!", time: "6h ago" },
      { id: 223, user: "freya.wax", text: "I prefer the 1981 but both are essential. That is the beauty of vinyl collecting.", time: "5h ago" },
    ],
    bookmarked: false,
    timeAgo: "5d ago",
    createdAt: now - 122 * hr,
    accent: "#6366f1",
    reactions: { fire: 7, heart: 12, vinyl: 4 },
    views: 168,
  },
  {
    id: 2093,
    user: "zara.grooves",
    type: "photo",
    caption: "Reggae shelf reorganized by label. Island Records on top, Studio One in the middle, Trojan at the bottom. The Heart of the Congos gets pride of place. Lee Scratch Perry was operating on another wavelength entirely.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Heart of the Congos", artist: "The Congos" },
    likes: 31,
    liked: false,
    comments: [
      { id: 224, user: "sol.spins", text: "Studio One pressings are getting harder and harder to find in good condition.", time: "7h ago" },
      { id: 225, user: "mara.vinyl", text: "That Perry production is so far ahead of its time. Dub as architecture.", time: "6h ago" },
    ],
    bookmarked: false,
    timeAgo: "6d ago",
    createdAt: now - 140 * hr,
    accent: "#22c55e",
    reactions: { fire: 14, heart: 9, vinyl: 8 },
    views: 221,
  },
  {
    id: 2094,
    user: "sol.spins",
    type: "review",
    caption: "Fela Kuti's Expensive Shit is protest music at its most fearless. The Nigerian government tried to plant drugs on him and he literally swallowed the evidence. Then he wrote this album about it. The groove is 13 minutes of pure defiance.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Expensive Shit", artist: "Fela Kuti" },
    likes: 35,
    liked: false,
    comments: [
      { id: 226, user: "kofi.grooves", text: "Fela is the most important African musician of the 20th century. No debate.", time: "8h ago" },
      { id: 227, user: "nadia.rpm", text: "The Afrobeat groove is so infectious. Once you are in it you never want to leave.", time: "7h ago" },
    ],
    bookmarked: false,
    timeAgo: "6d ago",
    createdAt: now - 145 * hr,
    accent: "#10b981",
    reactions: { fire: 18, heart: 11, vinyl: 7 },
    views: 256,
  },
  {
    id: 2095,
    user: "elena.rpm",
    type: "review",
    caption: "Paco de Lucia changed flamenco guitar forever with Entre dos aguas. He bridged tradition and modernity without losing the soul of either. This Philips pressing from Spain has warmth that later reissues flatten out.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Fuente y Caudal", artist: "Paco de Lucia" },
    likes: 19,
    liked: false,
    comments: [
      { id: 228, user: "mateo.spins", text: "Flamenco on vinyl is a transcendent experience. The percussive attack of the guitar comes through perfectly.", time: "9h ago" },
    ],
    bookmarked: false,
    timeAgo: "7d ago",
    createdAt: now - 160 * hr,
    accent: "#ca8a04",
    reactions: { fire: 8, heart: 7, vinyl: 3 },
    views: 142,
  },
  {
    id: 2096,
    user: "emi.spins",
    type: "review",
    caption: "Stravinsky's Rite of Spring caused a literal riot at its 1913 premiere. This Boulez/Cleveland recording captures that primal energy perfectly. The Sacrificial Dance on vinyl will shake your walls and terrify your neighbors.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "The Rite of Spring", artist: "Igor Stravinsky (Boulez / Cleveland)" },
    likes: 17,
    liked: false,
    comments: [
      { id: 229, user: "petra.spins", text: "Boulez brings surgical precision AND raw power. The best of both worlds.", time: "10h ago" },
      { id: 230, user: "freya.wax", text: "Classical music on vinyl is an underrated experience. The dynamics are unmatched.", time: "9h ago" },
    ],
    bookmarked: false,
    timeAgo: "7d ago",
    createdAt: now - 165 * hr,
    accent: "#6366f1",
    reactions: { fire: 6, heart: 9, vinyl: 3 },
    views: 131,
  },
  {
    id: 2097,
    user: "hal.grooves",
    type: "photo",
    caption: "Blues shelf tour. Delta blues at the top, Chicago blues in the middle, Texas blues at the bottom. Robert Johnson, Muddy Waters, B.B. King, Albert King, SRV. The entire evolution of the blues in one shelf.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Born Under a Bad Sign", artist: "Albert King" },
    likes: 24,
    liked: false,
    comments: [
      { id: 231, user: "thomas.wax", text: "The blues shelf is always the most honest section of any collection.", time: "11h ago" },
      { id: 232, user: "lena.records", text: "Albert King on Stax is peak blues. That Flying V tone!", time: "10h ago" },
    ],
    bookmarked: false,
    timeAgo: "8d ago",
    createdAt: now - 185 * hr,
    accent: "#2563eb",
    reactions: { fire: 11, heart: 8, vinyl: 5 },
    views: 178,
  },
  {
    id: 2098,
    user: "mateo.spins",
    type: "review",
    caption: "Willie Colon and Ruben Blades made Siembra, the best-selling salsa album of all time. Pedro Navaja is seven minutes of storytelling perfection set to the tightest rhythm section in Latin music history. Original Fania pressing.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Siembra", artist: "Willie Colon & Ruben Blades" },
    likes: 26,
    liked: false,
    comments: [
      { id: 233, user: "elena.rpm", text: "Fania Records was the Motown of salsa. Every release is essential.", time: "12h ago" },
      { id: 234, user: "sol.spins", text: "Latin vinyl is so underappreciated in the collecting world. These pressings deserve more love.", time: "11h ago" },
    ],
    bookmarked: false,
    timeAgo: "8d ago",
    createdAt: now - 190 * hr,
    accent: "#b91c1c",
    reactions: { fire: 13, heart: 7, vinyl: 6 },
    views: 195,
  },
  {
    id: 2099,
    user: "zara.grooves",
    type: "review",
    caption: "Augustus Pablo and King Tubby created the definitive dub album with King Tubby Meets Rockers Uptown. The melodica floats through vast spaces of echo and reverb. This is music that builds entire worlds from rhythm and empty space.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "King Tubby Meets Rockers Uptown", artist: "Augustus Pablo" },
    likes: 29,
    liked: false,
    comments: [
      { id: 235, user: "juniper.sounds", text: "Dub is the most underrated genre in vinyl collecting. The production techniques were decades ahead.", time: "1d ago" },
      { id: 236, user: "beau.plays", text: "King Tubby invented remix culture. Everything electronic owes a debt to this album.", time: "22h ago" },
    ],
    bookmarked: false,
    timeAgo: "9d ago",
    createdAt: now - 210 * hr,
    accent: "#22c55e",
    reactions: { fire: 15, heart: 10, vinyl: 7 },
    views: 213,
  },
  {
    id: 2100,
    user: "hal.grooves",
    type: "review",
    caption: "Stevie Ray Vaughan's Texas Flood announced a guitar hero for a new generation. Pride and Joy, Love Struck Baby, and the title track are ferocious. This original Epic pressing is in near mint condition and sounds absolutely massive.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Texas Flood", artist: "Stevie Ray Vaughan" },
    likes: 33,
    liked: false,
    comments: [
      { id: 237, user: "bjorn.grooves", text: "SRV brought the blues back to the mainstream in the 80s. What a debut.", time: "1d ago" },
      { id: 238, user: "thomas.wax", text: "That guitar tone could cut through steel. Absolute legend.", time: "20h ago" },
    ],
    bookmarked: false,
    timeAgo: "10d ago",
    createdAt: now - 235 * hr,
    accent: "#2563eb",
    reactions: { fire: 16, heart: 12, vinyl: 5 },
    views: 247,
  },
];

// Enrich all posts with reactions and views if not already present
const ENRICHED_POSTS = INITIAL_POSTS.map(post => ({
  ...post,
  reactions: post.reactions || _reactionSeed(post.id),
  views: post.views || _viewSeed(post.id),
}));

export default ENRICHED_POSTS;
