// Seed data for the social feed — user-created posts with optional tagged records.
// Posts are separate from the record catalog; they're social content that can reference any record.
// Shape: { id, user, caption, mediaUrl?, mediaType, taggedRecord?, likes, liked, comments[], bookmarked, timeAgo, createdAt, accent }

const now = Date.now();

const INITIAL_POSTS = [
  {
    id: 2001,
    user: "mara.vinyl",
    caption: "Found this original Impulse! pressing at a garage sale for $3. The vinyl gods were smiling today. The deep groove pressing sounds absolutely incredible through the Ortofon 2M Blue.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "A Love Supreme", artist: "John Coltrane" },
    likes: 34,
    liked: false,
    comments: [
      { id: 1, user: "felix.rpm", text: "No way!! That's an incredible find! 🔥", time: "3h ago" },
      { id: 2, user: "yuki.vinyl", text: "The vinyl gods indeed. I've been hunting this for years.", time: "2h ago" },
      { id: 3, user: "soren.stacks", text: "Deep groove Impulse pressings are the holy grail. Congrats!", time: "1h ago" },
    ],
    bookmarked: false,
    timeAgo: "4h ago",
    createdAt: now - 14400000,
    accent: "#ec4899",
  },
  {
    id: 2002,
    user: "nadia.rpm",
    caption: "Saturday morning ritual. Coffee, this record, and absolutely nothing else. Hip-hop doesn't get more perfect than this.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Illmatic", artist: "Nas" },
    likes: 47,
    liked: false,
    comments: [
      { id: 4, user: "dax.wax", text: "The greatest hip-hop album ever made. No debate.", time: "5h ago" },
      { id: 5, user: "max.plays", text: "Every single track is a 10/10", time: "4h ago" },
    ],
    bookmarked: false,
    timeAgo: "6h ago",
    createdAt: now - 21600000,
    accent: "#8b5cf6",
  },
  {
    id: 2003,
    user: "juniper.sounds",
    caption: "Just reorganized my entire electronic section by BPM instead of alphabetically. Is this what going too far looks like? Anyway here's the crown jewel of the collection.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Selected Ambient Works 85-92", artist: "Aphex Twin" },
    likes: 29,
    liked: false,
    comments: [
      { id: 6, user: "beau.plays", text: "Organizing by BPM is galaxy brain actually", time: "8h ago" },
      { id: 7, user: "otto.wax", text: "I organize mine by mood. We are not the same.", time: "7h ago" },
    ],
    bookmarked: false,
    timeAgo: "9h ago",
    createdAt: now - 32400000,
    accent: "#f97316",
  },
  {
    id: 2004,
    user: "thomas.wax",
    caption: "My turntable setup got a major upgrade today. New Rega Planar 3 with an Exact cartridge. First spin had to be the classics. The separation on this pressing is unreal.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Led Zeppelin IV", artist: "Led Zeppelin" },
    likes: 52,
    liked: false,
    comments: [
      { id: 8, user: "bjorn.grooves", text: "Rega Planar 3 is incredible for the price. Great choice!", time: "10h ago" },
      { id: 9, user: "iris.rpm", text: "The acoustic guitar on Going to California through a good setup... *chefs kiss*", time: "9h ago" },
      { id: 10, user: "thomas.wax", text: "Exactly!! And the dynamics on When the Levee Breaks 🤯", time: "8h ago" },
    ],
    bookmarked: false,
    timeAgo: "11h ago",
    createdAt: now - 39600000,
    accent: "#a78bfa",
  },
  {
    id: 2005,
    user: "yuki.vinyl",
    caption: "City pop deep cut alert. Picked this up in Shibuya last month. The bass line on side B is pure serotonin. If you know, you know.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Pacific", artist: "Haruomi Hosono" },
    likes: 38,
    liked: false,
    comments: [
      { id: 11, user: "juniper.sounds", text: "City pop on vinyl hits different. That warm analog sound!", time: "12h ago" },
      { id: 12, user: "mara.vinyl", text: "Adding this to my want list immediately", time: "11h ago" },
    ],
    bookmarked: false,
    timeAgo: "14h ago",
    createdAt: now - 50400000,
    accent: "#f59e0b",
  },
  {
    id: 2006,
    user: "cleo.spins",
    caption: "Shoegaze Sunday. Turned the lights off, cranked the volume, and let the noise wash over me. This album is a religious experience on vinyl.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Loveless", artist: "My Bloody Valentine" },
    likes: 41,
    liked: false,
    comments: [
      { id: 13, user: "otto.wax", text: "The way the guitars blur together on Only Shallow... transcendent", time: "16h ago" },
      { id: 14, user: "cass.stacks", text: "Best album ever made. Fight me.", time: "15h ago" },
    ],
    bookmarked: false,
    timeAgo: "18h ago",
    createdAt: now - 64800000,
    accent: "#84cc16",
  },
  {
    id: 2007,
    user: "max.plays",
    caption: "Store pickup of the week! Customer brought in a box of records and this was hiding at the bottom. Original pressing, plays clean. Sometimes the best crates find you.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Maggot Brain", artist: "Funkadelic" },
    likes: 56,
    liked: false,
    comments: [
      { id: 15, user: "dax.wax", text: "That opening guitar solo is 10 minutes of pure emotion", time: "20h ago" },
      { id: 16, user: "lena.records", text: "Eddie Hazel played that solo as if his mother just died. Because George Clinton told him to imagine that.", time: "19h ago" },
      { id: 17, user: "felix.rpm", text: "One of the greatest guitar performances ever recorded", time: "18h ago" },
    ],
    bookmarked: false,
    timeAgo: "22h ago",
    createdAt: now - 79200000,
    accent: "#a78bfa",
  },
  {
    id: 2008,
    user: "felix.rpm",
    caption: "Late night jazz session. There's something about Herbie's Rhodes playing on this album that just puts you in another dimension. The Headhunters were so tight.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Head Hunters", artist: "Herbie Hancock" },
    likes: 33,
    liked: false,
    comments: [
      { id: 18, user: "mara.vinyl", text: "Chameleon is the song that got me into jazz. Forever grateful.", time: "1d ago" },
      { id: 19, user: "soren.stacks", text: "Jazz-funk perfection. Every musician should study this album.", time: "1d ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 86400000,
    accent: "#06b6d4",
  },
  {
    id: 2009,
    user: "otto.wax",
    caption: "Berlin flea market haul. Found a German pressing of Unknown Pleasures with the textured sleeve intact. Peter Saville's cover design is even more stunning in person.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Unknown Pleasures", artist: "Joy Division" },
    likes: 44,
    liked: false,
    comments: [
      { id: 20, user: "cass.stacks", text: "German pressings sound incredible. Factory Records quality.", time: "1d ago" },
      { id: 21, user: "cleo.spins", text: "That cover is literally hanging on my wall as a poster", time: "1d ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 100800000,
    accent: "#ef4444",
  },
  {
    id: 2010,
    user: "lena.records",
    caption: "What's Going On was released 55 years ago and every word still hits. Marvin was ahead of his time. This is the album I play when the world feels heavy.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "What's Going On", artist: "Marvin Gaye" },
    likes: 61,
    liked: false,
    comments: [
      { id: 22, user: "nadia.rpm", text: "Timeless. One of the most important albums ever made.", time: "1d ago" },
      { id: 23, user: "max.plays", text: "The string arrangements on this album are absolutely gorgeous", time: "1d ago" },
      { id: 24, user: "zara.grooves", text: "Mercy Mercy Me still gives me chills every time", time: "1d ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 115200000,
    accent: "#ec4899",
  },
  {
    id: 2011,
    user: "bjorn.grooves",
    caption: "Finally got my hands on a clean copy. The riffs on this record literally invented a genre. Played it three times back to back and my neighbors are not happy.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Master of Puppets", artist: "Metallica" },
    likes: 39,
    liked: false,
    comments: [
      { id: 25, user: "riku.records", text: "GOAT metal album. Orion alone makes it a masterpiece.", time: "2d ago" },
      { id: 26, user: "thomas.wax", text: "Even as a rock guy I can appreciate the musicianship here", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 172800000,
    accent: "#10b981",
  },
  {
    id: 2012,
    user: "beau.plays",
    caption: "Every Friday night needs a proper warm-up. This is mine. French house forever. The sample work on this album changed dance music.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Homework", artist: "Daft Punk" },
    likes: 45,
    liked: false,
    comments: [
      { id: 27, user: "juniper.sounds", text: "Da Funk into Rollin & Scratchin is the best 1-2 punch in electronic music", time: "2d ago" },
      { id: 28, user: "beau.plays", text: "Absolutely! The energy never drops", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 180000000,
    accent: "#f59e0b",
  },
  {
    id: 2013,
    user: "milo.vinyl",
    caption: "Rainy afternoon, hot tea, and Nick Drake. This is what vinyl was made for. The intimacy of Pink Moon on a good system is unmatched.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Pink Moon", artist: "Nick Drake" },
    likes: 28,
    liked: false,
    comments: [
      { id: 29, user: "cleo.spins", text: "Nick Drake's voice in a quiet room is pure therapy", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 259200000,
    accent: "#84cc16",
  },
  {
    id: 2014,
    user: "dax.wax",
    caption: "Dollar bin treasure! Found this absolute gem for $0.50. The cover is beat up but the record plays VG+. This is why I dig. You never know what's hiding in those cheap bins.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "There's a Riot Goin' On", artist: "Sly & The Family Stone" },
    likes: 36,
    liked: false,
    comments: [
      { id: 30, user: "max.plays", text: "Dollar bin king strikes again! Great find.", time: "3d ago" },
      { id: 31, user: "lena.records", text: "Family Affair is such a vibe. Incredible album.", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 270000000,
    accent: "#06b6d4",
  },
  {
    id: 2015,
    user: "zara.grooves",
    caption: "Turned my living room into Kingston for the evening. Burning incense, this on the turntable, and nowhere to be. Pure bliss.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Catch a Fire", artist: "Bob Marley & The Wailers" },
    likes: 31,
    liked: false,
    comments: [
      { id: 32, user: "felix.rpm", text: "Island Records pressings of the Wailers stuff sound so good!", time: "4d ago" },
    ],
    bookmarked: false,
    timeAgo: "4d ago",
    createdAt: now - 345600000,
    accent: "#10b981",
  },
  // ── New posts below ────────────────────────────────────────────────────────
  {
    id: 2016,
    user: "creator",
    caption: "Finally pulled the trigger on a proper cleaning setup. Spin-Clean record washer + new inner sleeves for the whole collection. Spent all weekend cleaning and re-sleeving. My records have never sounded this good.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 22,
    liked: false,
    comments: [
      { id: 33, user: "thomas.wax", text: "Spin-Clean is the best $80 you can spend in this hobby", time: "1h ago" },
      { id: 34, user: "mara.vinyl", text: "MoFi inner sleeves are the way. Congrats on the upgrade!", time: "45m ago" },
    ],
    bookmarked: false,
    timeAgo: "2h ago",
    createdAt: now - 7200000,
    accent: "#0ea5e9",
  },
  {
    id: 2017,
    user: "creator",
    caption: "Just picked this up from the local shop. The six-eye Columbia mono pressing. Forty years of searching and it finally happened. My hands are still shaking.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Kind of Blue", artist: "Miles Davis" },
    likes: 78,
    liked: false,
    comments: [
      { id: 35, user: "mara.vinyl", text: "SIX-EYE MONO?! I'm genuinely jealous. Congratulations!", time: "5h ago" },
      { id: 36, user: "felix.rpm", text: "That might be the single greatest jazz pressing you can own", time: "4h ago" },
      { id: 37, user: "soren.stacks", text: "The holy grail. Enjoy every second of it.", time: "3h ago" },
      { id: 38, user: "yuki.vinyl", text: "I need to hear this. Next time I'm in town, I'm coming over.", time: "2h ago" },
    ],
    bookmarked: false,
    timeAgo: "6h ago",
    createdAt: now - 21600000,
    accent: "#0ea5e9",
  },
  {
    id: 2018,
    user: "petra.spins",
    caption: "The Goldberg Variations on vinyl is a completely different experience from digital. You can hear Glenn Gould humming along. The analog warmth makes the piano sound so much more present.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Goldberg Variations", artist: "Glenn Gould" },
    likes: 19,
    liked: false,
    comments: [
      { id: 39, user: "soren.stacks", text: "Gould's humming is half the charm. A truly intimate recording.", time: "6h ago" },
    ],
    bookmarked: false,
    timeAgo: "8h ago",
    createdAt: now - 28800000,
    accent: "#ef4444",
  },
  {
    id: 2019,
    user: "riku.records",
    caption: "Hot take: Blackwater Park is Opeth's best album and it's not even close. The dynamics between the quiet acoustic sections and the crushing heaviness are unmatched in metal.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Blackwater Park", artist: "Opeth" },
    likes: 27,
    liked: false,
    comments: [
      { id: 40, user: "bjorn.grooves", text: "This is not a hot take, it's just facts. The Drapery Falls is transcendent.", time: "10h ago" },
      { id: 41, user: "cass.stacks", text: "Still Life is close but yeah, this one edges it out", time: "9h ago" },
    ],
    bookmarked: false,
    timeAgo: "12h ago",
    createdAt: now - 43200000,
    accent: "#8b5cf6",
  },
  {
    id: 2020,
    user: "soren.stacks",
    caption: "Quiet evening in Copenhagen. Rain on the windows and this on the turntable. There is no better ambient album. The textures are so delicate they almost disappear.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Music for Airports", artist: "Brian Eno" },
    likes: 24,
    liked: false,
    comments: [
      { id: 42, user: "juniper.sounds", text: "Eno basically invented ambient music with this record. Timeless.", time: "14h ago" },
      { id: 43, user: "mara.vinyl", text: "I fall asleep to this at least once a week. In the best way.", time: "13h ago" },
    ],
    bookmarked: false,
    timeAgo: "16h ago",
    createdAt: now - 57600000,
    accent: "#0ea5e9",
  },
  {
    id: 2021,
    user: "iris.rpm",
    caption: "Unpopular opinion: Tales from Topographic Oceans is actually good. Yes, all four sides. I will not be taking questions at this time.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Tales from Topographic Oceans", artist: "Yes" },
    likes: 15,
    liked: false,
    comments: [
      { id: 44, user: "thomas.wax", text: "I respect the commitment even if I can't make it past side two", time: "1d ago" },
      { id: 45, user: "riku.records", text: "Prog heads unite. This album is a journey and I love every minute.", time: "1d ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 93600000,
    accent: "#f97316",
  },
  {
    id: 2022,
    user: "cass.stacks",
    caption: "Just got back from a punk show at Whelan's and had to come home and put this on. Nothing sounds more alive than the first Clash album after a sweaty gig.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "The Clash", artist: "The Clash" },
    likes: 33,
    liked: false,
    comments: [
      { id: 46, user: "otto.wax", text: "Post-show vinyl sessions are the best. What did you see?", time: "20h ago" },
      { id: 47, user: "cass.stacks", text: "Local band called The Drowning Men. Absolute chaos. Loved it.", time: "19h ago" },
    ],
    bookmarked: false,
    timeAgo: "22h ago",
    createdAt: now - 79200000,
    accent: "#0ea5e9",
  },
  {
    id: 2023,
    user: "creator",
    caption: "Three years of collecting and I just hit 500 records. Here's a shelf shot. Some of you might recognize a few grails in there. What a journey it's been.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 91,
    liked: false,
    comments: [
      { id: 48, user: "max.plays", text: "500 club! Welcome. It only gets worse from here 😅", time: "2d ago" },
      { id: 49, user: "dax.wax", text: "I see that Blue Note spine... is that an original Coltrane?", time: "2d ago" },
      { id: 50, user: "creator", text: "Good eye! Blue Train, deep groove pressing.", time: "2d ago" },
      { id: 51, user: "mara.vinyl", text: "Incredible collection. That top shelf is pure class.", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 172800000,
    accent: "#0ea5e9",
  },
  {
    id: 2024,
    user: "nadia.rpm",
    caption: "Question for the timeline: what's the one album that got you into vinyl? For me it was this. Heard it on a friend's turntable in college and never went back to streaming.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Ready to Die", artist: "The Notorious B.I.G." },
    likes: 58,
    liked: false,
    comments: [
      { id: 52, user: "thomas.wax", text: "Led Zeppelin IV at my uncle's house. Changed everything.", time: "1d ago" },
      { id: 53, user: "mara.vinyl", text: "Kind of Blue on my mom's old turntable. I was 14.", time: "1d ago" },
      { id: 54, user: "cleo.spins", text: "Siamese Dream. The guitar tones on vinyl were a revelation.", time: "1d ago" },
      { id: 55, user: "beau.plays", text: "Discovery by Daft Punk. The gatefold artwork sealed the deal.", time: "23h ago" },
      { id: 56, user: "lena.records", text: "Otis Redding - Otis Blue. My dad's copy. Still have it.", time: "22h ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 108000000,
    accent: "#8b5cf6",
  },
  {
    id: 2025,
    user: "juniper.sounds",
    caption: "New Burial 12-inch arrived. The man continues to make music that sounds like 3am in a city you've never been to. Hyperdub never misses.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Untrue", artist: "Burial" },
    likes: 37,
    liked: false,
    comments: [
      { id: 57, user: "beau.plays", text: "Archangel on vinyl in a dark room is a spiritual experience", time: "3d ago" },
      { id: 58, user: "otto.wax", text: "3am in a city you've never been to is the most accurate description of Burial I've ever read", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 259200000,
    accent: "#f97316",
  },
  {
    id: 2026,
    user: "lena.records",
    caption: "Atlantic Records pressings from the late 60s just hit different. The mastering, the pressing quality, the cover art. They don't make them like this anymore.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "I Never Loved a Man the Way I Love You", artist: "Aretha Franklin" },
    likes: 43,
    liked: false,
    comments: [
      { id: 59, user: "max.plays", text: "Respect is the greatest vocal performance ever recorded. Change my mind.", time: "2d ago" },
      { id: 60, user: "zara.grooves", text: "Those Atlantic soul records are pure gold. Every one.", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 194400000,
    accent: "#ec4899",
  },
  {
    id: 2027,
    user: "max.plays",
    caption: "Priced some new arrivals for the shop today. Had to sit down and listen to this one before putting it on the shelf. Almost kept it for myself. Almost.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Standing on the Verge of Getting It On", artist: "Funkadelic" },
    likes: 29,
    liked: false,
    comments: [
      { id: 61, user: "dax.wax", text: "How much?? I'm on my way.", time: "4d ago" },
      { id: 62, user: "max.plays", text: "$35. First come first served. And no, I'm not holding it.", time: "4d ago" },
      { id: 63, user: "felix.rpm", text: "The title track is INSANE. One of the tightest funk performances ever.", time: "4d ago" },
    ],
    bookmarked: false,
    timeAgo: "4d ago",
    createdAt: now - 345600000,
    accent: "#a78bfa",
  },
  {
    id: 2028,
    user: "yuki.vinyl",
    caption: "Spent the morning at Disk Union in Shibuya. The J-jazz section there is unbelievable. Walked out with five records and an empty wallet. Zero regrets.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 42,
    liked: false,
    comments: [
      { id: 64, user: "mara.vinyl", text: "Disk Union is vinyl paradise. I'm so jealous you get to go regularly.", time: "5d ago" },
      { id: 65, user: "soren.stacks", text: "What did you pick up? Drop the haul!", time: "5d ago" },
      { id: 66, user: "yuki.vinyl", text: "Ryo Fukui, Masabumi Kikuchi, Terumasa Hino, and two Sadao Watanabe records. All originals.", time: "5d ago" },
    ],
    bookmarked: false,
    timeAgo: "5d ago",
    createdAt: now - 432000000,
    accent: "#f59e0b",
  },
  {
    id: 2029,
    user: "bjorn.grooves",
    caption: "Controversial ranking time: Black Sabbath > Paranoid. The self-titled has a rawness that Paranoid polished away. Both are masterpieces but the debut is where it all started.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Black Sabbath", artist: "Black Sabbath" },
    likes: 35,
    liked: false,
    comments: [
      { id: 67, user: "riku.records", text: "Absolutely correct. The self-titled invented doom metal in real time.", time: "3d ago" },
      { id: 68, user: "thomas.wax", text: "That opening tritone on Black Sabbath... still the heaviest riff ever written.", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 280800000,
    accent: "#10b981",
  },
  {
    id: 2030,
    user: "creator",
    caption: "Anyone else find that certain records just sound better at specific times of day? This one is strictly a midnight record for me. Something about the atmosphere of Blonde at night.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Blonde", artist: "Frank Ocean" },
    likes: 64,
    liked: false,
    comments: [
      { id: 69, user: "nadia.rpm", text: "Blonde is 100% a 2am album. Nights hits differently when it's actually nighttime.", time: "1d ago" },
      { id: 70, user: "cleo.spins", text: "Self Control at midnight with headphones. That's the move.", time: "1d ago" },
      { id: 71, user: "juniper.sounds", text: "Morning records, afternoon records, evening records. We all do this right?", time: "23h ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 129600000,
    accent: "#0ea5e9",
  },
  {
    id: 2031,
    user: "dax.wax",
    caption: "Garage sale season is officially open. Hit four sales before 8am. Total haul: 23 records for $12. Quality? We'll see when I get home and clean them up.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 48,
    liked: false,
    comments: [
      { id: 72, user: "max.plays", text: "The early bird gets the wax. What neighborhoods?", time: "5d ago" },
      { id: 73, user: "dax.wax", text: "Southwest Detroit. Old Motown territory. You'd be surprised what turns up.", time: "5d ago" },
    ],
    bookmarked: false,
    timeAgo: "5d ago",
    createdAt: now - 453600000,
    accent: "#06b6d4",
  },
  {
    id: 2032,
    user: "mara.vinyl",
    caption: "Spent the afternoon deep-cleaning my jazz shelves. Re-organized by label instead of artist. Blue Note, Prestige, Impulse!, Riverside. Looks incredible. Sounds even better.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 26,
    liked: false,
    comments: [
      { id: 74, user: "felix.rpm", text: "Label organization is so satisfying. All those Blue Note spines lined up...", time: "6d ago" },
      { id: 75, user: "soren.stacks", text: "ECM section must look pristine with those clean white spines", time: "6d ago" },
    ],
    bookmarked: false,
    timeAgo: "6d ago",
    createdAt: now - 518400000,
    accent: "#ec4899",
  },
  {
    id: 2033,
    user: "zara.grooves",
    caption: "Lee Scratch Perry was a genius and I will never stop saying it. The production on this record sounds like it was beamed in from another planet. RIP the Upsetter.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Super Ape", artist: "Lee \"Scratch\" Perry" },
    likes: 30,
    liked: false,
    comments: [
      { id: 76, user: "felix.rpm", text: "The Black Ark studio recordings are some of the most creative music ever made", time: "4d ago" },
    ],
    bookmarked: false,
    timeAgo: "4d ago",
    createdAt: now - 367200000,
    accent: "#10b981",
  },
  {
    id: 2034,
    user: "beau.plays",
    caption: "Saturday night in Paris. Friends over, turntable warm, and this on repeat. Disco is alive and well in this apartment.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Random Access Memories", artist: "Daft Punk" },
    likes: 51,
    liked: false,
    comments: [
      { id: 77, user: "juniper.sounds", text: "Giorgio by Moroder is the most fun track on any album ever", time: "1d ago" },
      { id: 78, user: "yuki.vinyl", text: "Touch still makes me emotional every single time", time: "1d ago" },
      { id: 79, user: "beau.plays", text: "Lose Yourself to Dance at volume is pure joy. The apartment was shaking.", time: "22h ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 140400000,
    accent: "#f59e0b",
  },
  {
    id: 2035,
    user: "otto.wax",
    caption: "Does anyone else have a record they keep buying different pressings of? I now own four copies of Closer. The Factory original, the 2007 remaster, the 2015 remaster, and a Japanese pressing. I might have a problem.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Closer", artist: "Joy Division" },
    likes: 38,
    liked: false,
    comments: [
      { id: 80, user: "cleo.spins", text: "I have three copies of Loveless so I'm not judging", time: "2d ago" },
      { id: 81, user: "cass.stacks", text: "This is just collecting at an advanced level. Embrace it.", time: "2d ago" },
      { id: 82, user: "thomas.wax", text: "I have five Zep IVs. Different masterings, different magic.", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 205200000,
    accent: "#ef4444",
  },
  {
    id: 2036,
    user: "milo.vinyl",
    caption: "First listen of the day. Coffee hasn't even kicked in yet. There's something about folk music in the morning that just feels right. The world is quiet and so is this record.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "For Emma, Forever Ago", artist: "Bon Iver" },
    likes: 21,
    liked: false,
    comments: [
      { id: 83, user: "cleo.spins", text: "Skinny Love on vinyl in the morning... that's meditation.", time: "6d ago" },
    ],
    bookmarked: false,
    timeAgo: "6d ago",
    createdAt: now - 540000000,
    accent: "#84cc16",
  },
  {
    id: 2037,
    user: "creator",
    caption: "Marketplace find: someone was selling their entire Warp Records collection. I grabbed what I could. Aphex Twin, Autechre, Boards of Canada, Squarepusher. Best $200 I've ever spent.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 55,
    liked: false,
    comments: [
      { id: 84, user: "juniper.sounds", text: "A WHOLE WARP COLLECTION? I'm genuinely upset I missed this.", time: "3d ago" },
      { id: 85, user: "beau.plays", text: "Boards of Canada on vinyl is a must. Which ones did you get?", time: "3d ago" },
      { id: 86, user: "creator", text: "Music Has the Right to Children and Geogaddi. Both NM.", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 280800000,
    accent: "#0ea5e9",
  },
  {
    id: 2038,
    user: "nico.crates",
    caption: "New to GrooveStack! Just moved to LA and looking to connect with other collectors. My thing is 70s Brazilian music — bossa nova, tropicalia, MPB. Hit me up if you're into it.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 18,
    liked: false,
    comments: [
      { id: 87, user: "felix.rpm", text: "Welcome! You need to check out the marketplace. Some great Brazilian records pop up.", time: "1d ago" },
      { id: 88, user: "yuki.vinyl", text: "Love bossa nova. What's your favorite Jobim record?", time: "1d ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 151200000,
    accent: "#f97316",
  },
  {
    id: 2039,
    user: "ada.tracks",
    caption: "Finally set up my listening room properly. Acoustic panels, dedicated circuit, and the turntable on a wall-mounted shelf to kill vibration. The difference is staggering. Every record sounds new again.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 40,
    liked: false,
    comments: [
      { id: 89, user: "thomas.wax", text: "Dedicated circuit is so underrated. Huge upgrade for the money.", time: "4d ago" },
      { id: 90, user: "mara.vinyl", text: "Wall-mounted shelf is genius. No more footstep vibration.", time: "4d ago" },
      { id: 91, user: "petra.spins", text: "Acoustic treatment makes such a difference. What panels did you go with?", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "4d ago",
    createdAt: now - 367200000,
    accent: "#84cc16",
  },
  {
    id: 2040,
    user: "kai.wax",
    caption: "Record Store Day haul from Rough Trade. Got there at 5am and it was worth every minute of lost sleep. The Radiohead reissue alone made the trip.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "OK Computer", artist: "Radiohead" },
    likes: 46,
    liked: false,
    comments: [
      { id: 92, user: "cleo.spins", text: "RSD is the best and worst day of the year for collectors", time: "5d ago" },
      { id: 93, user: "juniper.sounds", text: "What pressing? The OKNOTOK boxset?", time: "5d ago" },
      { id: 94, user: "kai.wax", text: "The blue vinyl repress. Sounds absolutely incredible.", time: "5d ago" },
    ],
    bookmarked: false,
    timeAgo: "5d ago",
    createdAt: now - 453600000,
    accent: "#a78bfa",
  },
  {
    id: 2041,
    user: "sol.spins",
    caption: "Anyone here into Afrobeat? Been diving deep into the Fela Kuti catalog on vinyl. The 15-minute tracks are made for the LP format. This is where the music breathes.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Zombie", artist: "Fela Kuti" },
    likes: 33,
    liked: false,
    comments: [
      { id: 95, user: "zara.grooves", text: "Fela is essential. Zombie is the perfect entry point.", time: "2d ago" },
      { id: 96, user: "max.plays", text: "We just got a stack of Fela reissues at the shop. Come through!", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 216000000,
    accent: "#10b981",
  },
  {
    id: 2042,
    user: "tova.vinyl",
    caption: "My grandmother gave me her record collection today. Over 200 records from the 50s and 60s. Sinatra, Ella, Billie Holiday, Nina Simone. I'm not crying, you're crying.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 87,
    liked: false,
    comments: [
      { id: 97, user: "lena.records", text: "That's incredibly special. What a gift. Treasure those.", time: "3d ago" },
      { id: 98, user: "mara.vinyl", text: "Original 50s jazz vocals on vinyl? That's a goldmine of warmth.", time: "3d ago" },
      { id: 99, user: "felix.rpm", text: "Nina Simone on original vinyl is something else entirely. You're lucky.", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 302400000,
    accent: "#ec4899",
  },
  {
    id: 2043,
    user: "creator",
    caption: "Sunday listening stack. Left to right: Coltrane, Mingus, Miles, Monk. Four pillars, four hours, four cups of coffee. This is what weekends are for.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: null,
    likes: 72,
    liked: false,
    comments: [
      { id: 100, user: "mara.vinyl", text: "The perfect Sunday. Which Monk record?", time: "1d ago" },
      { id: 101, user: "creator", text: "Brilliant Corners. Always Brilliant Corners.", time: "1d ago" },
      { id: 102, user: "soren.stacks", text: "This is the way. No distractions, just music.", time: "22h ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 162000000,
    accent: "#0ea5e9",
  },
  {
    id: 2044,
    user: "wren.stacks",
    caption: "PSA: if you're sleeping on Khruangbin you are missing out. Their live recordings on vinyl are some of the best pressing I've heard in years. The low end is unreal.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Con Todo El Mundo", artist: "Khruangbin" },
    likes: 39,
    liked: false,
    comments: [
      { id: 103, user: "felix.rpm", text: "Maria Tambien is the song of the decade. So groovy.", time: "4d ago" },
      { id: 104, user: "dax.wax", text: "Everything they touch is gold. The pressing quality is chef's kiss.", time: "4d ago" },
    ],
    bookmarked: false,
    timeAgo: "4d ago",
    createdAt: now - 388800000,
    accent: "#06b6d4",
  },
  {
    id: 2045,
    user: "thomas.wax",
    caption: "Dusted off the old Technics SL-1200 today. Twenty years old and still runs like a dream. They really don't build them like they used to. First spin: side A of Who's Next.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Who's Next", artist: "The Who" },
    likes: 44,
    liked: false,
    comments: [
      { id: 105, user: "bjorn.grooves", text: "SL-1200 is bulletproof. Mine is from 1998 and hasn't skipped a beat.", time: "5d ago" },
      { id: 106, user: "nadia.rpm", text: "Baba O'Riley on a 1200... that's how it was meant to be heard.", time: "5d ago" },
    ],
    bookmarked: false,
    timeAgo: "5d ago",
    createdAt: now - 475200000,
    accent: "#a78bfa",
  },
];

export default INITIAL_POSTS;
