// Seed data for the social feed — user-created posts with optional tagged records.
// Posts are separate from the record catalog; they're social content that can reference any record.
// Shape: { id, user, caption, mediaUrl?, mediaType, taggedRecord?, likes, liked, comments[], bookmarked, timeAgo, createdAt, accent }

const now = Date.now();

const INITIAL_POSTS = [
  {
    id: 2001,
    user: "mara.vinyl",
    caption: "Found this original Impulse! pressing at a garage sale for $3. The vinyl gods were smiling today. The deep groove pressing sounds absolutely incredible through the Ortofon 2M Blue.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "A Love Supreme", artist: "John Coltrane" },
    likes: 34,
    liked: false,
    comments: [
      { id: 1, user: "felix.rpm", text: "No way!! That's an incredible find! 🔥", time: "3h ago" },
      { id: 2, user: "yuki.vinyl", text: "The vinyl gods indeed. I've been hunting this for years.", time: "2h ago" },
      { id: 3, user: "soren.stacks", text: "Deep groove Impulse pressings are the holy grail. Congrats!", time: "1h ago" },
    ],
    bookmarked: false,
    timeAgo: "4h ago",
    createdAt: now - 14400000,
    accent: "#ec4899",
  },
  {
    id: 2002,
    user: "nadia.rpm",
    caption: "Saturday morning ritual. Coffee, this record, and absolutely nothing else. Hip-hop doesn't get more perfect than this.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Illmatic", artist: "Nas" },
    likes: 47,
    liked: false,
    comments: [
      { id: 4, user: "dax.wax", text: "The greatest hip-hop album ever made. No debate.", time: "5h ago" },
      { id: 5, user: "max.plays", text: "Every single track is a 10/10", time: "4h ago" },
    ],
    bookmarked: false,
    timeAgo: "6h ago",
    createdAt: now - 21600000,
    accent: "#8b5cf6",
  },
  {
    id: 2003,
    user: "juniper.sounds",
    caption: "Just reorganized my entire electronic section by BPM instead of alphabetically. Is this what going too far looks like? Anyway here's the crown jewel of the collection.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Selected Ambient Works 85-92", artist: "Aphex Twin" },
    likes: 29,
    liked: false,
    comments: [
      { id: 6, user: "beau.plays", text: "Organizing by BPM is galaxy brain actually", time: "8h ago" },
      { id: 7, user: "otto.wax", text: "I organize mine by mood. We are not the same.", time: "7h ago" },
    ],
    bookmarked: false,
    timeAgo: "9h ago",
    createdAt: now - 32400000,
    accent: "#f97316",
  },
  {
    id: 2004,
    user: "thomas.wax",
    caption: "My turntable setup got a major upgrade today. New Rega Planar 3 with an Exact cartridge. First spin had to be the classics. The separation on this pressing is unreal.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Led Zeppelin IV", artist: "Led Zeppelin" },
    likes: 52,
    liked: false,
    comments: [
      { id: 8, user: "bjorn.grooves", text: "Rega Planar 3 is incredible for the price. Great choice!", time: "10h ago" },
      { id: 9, user: "iris.rpm", text: "The acoustic guitar on Going to California through a good setup... *chefs kiss*", time: "9h ago" },
      { id: 10, user: "thomas.wax", text: "Exactly!! And the dynamics on When the Levee Breaks 🤯", time: "8h ago" },
    ],
    bookmarked: false,
    timeAgo: "11h ago",
    createdAt: now - 39600000,
    accent: "#a78bfa",
  },
  {
    id: 2005,
    user: "yuki.vinyl",
    caption: "City pop deep cut alert. Picked this up in Shibuya last month. The bass line on side B is pure serotonin. If you know, you know.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Pacific", artist: "Haruomi Hosono" },
    likes: 38,
    liked: false,
    comments: [
      { id: 11, user: "juniper.sounds", text: "City pop on vinyl hits different. That warm analog sound!", time: "12h ago" },
      { id: 12, user: "mara.vinyl", text: "Adding this to my want list immediately", time: "11h ago" },
    ],
    bookmarked: false,
    timeAgo: "14h ago",
    createdAt: now - 50400000,
    accent: "#f59e0b",
  },
  {
    id: 2006,
    user: "cleo.spins",
    caption: "Shoegaze Sunday. Turned the lights off, cranked the volume, and let the noise wash over me. This album is a religious experience on vinyl.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Loveless", artist: "My Bloody Valentine" },
    likes: 41,
    liked: false,
    comments: [
      { id: 13, user: "otto.wax", text: "The way the guitars blur together on Only Shallow... transcendent", time: "16h ago" },
      { id: 14, user: "cass.stacks", text: "Best album ever made. Fight me.", time: "15h ago" },
    ],
    bookmarked: false,
    timeAgo: "18h ago",
    createdAt: now - 64800000,
    accent: "#84cc16",
  },
  {
    id: 2007,
    user: "max.plays",
    caption: "Store pickup of the week! Customer brought in a box of records and this was hiding at the bottom. Original pressing, plays clean. Sometimes the best crates find you.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Maggot Brain", artist: "Funkadelic" },
    likes: 56,
    liked: false,
    comments: [
      { id: 15, user: "dax.wax", text: "That opening guitar solo is 10 minutes of pure emotion", time: "20h ago" },
      { id: 16, user: "lena.records", text: "Eddie Hazel played that solo as if his mother just died. Because George Clinton told him to imagine that.", time: "19h ago" },
      { id: 17, user: "felix.rpm", text: "One of the greatest guitar performances ever recorded", time: "18h ago" },
    ],
    bookmarked: false,
    timeAgo: "22h ago",
    createdAt: now - 79200000,
    accent: "#a78bfa",
  },
  {
    id: 2008,
    user: "felix.rpm",
    caption: "Late night jazz session. There's something about Herbie's Rhodes playing on this album that just puts you in another dimension. The Headhunters were so tight.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Head Hunters", artist: "Herbie Hancock" },
    likes: 33,
    liked: false,
    comments: [
      { id: 18, user: "mara.vinyl", text: "Chameleon is the song that got me into jazz. Forever grateful.", time: "1d ago" },
      { id: 19, user: "soren.stacks", text: "Jazz-funk perfection. Every musician should study this album.", time: "1d ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 86400000,
    accent: "#06b6d4",
  },
  {
    id: 2009,
    user: "otto.wax",
    caption: "Berlin flea market haul. Found a German pressing of Unknown Pleasures with the textured sleeve intact. Peter Saville's cover design is even more stunning in person.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Unknown Pleasures", artist: "Joy Division" },
    likes: 44,
    liked: false,
    comments: [
      { id: 20, user: "cass.stacks", text: "German pressings sound incredible. Factory Records quality.", time: "1d ago" },
      { id: 21, user: "cleo.spins", text: "That cover is literally hanging on my wall as a poster", time: "1d ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 100800000,
    accent: "#ef4444",
  },
  {
    id: 2010,
    user: "lena.records",
    caption: "What's Going On was released 55 years ago and every word still hits. Marvin was ahead of his time. This is the album I play when the world feels heavy.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "What's Going On", artist: "Marvin Gaye" },
    likes: 61,
    liked: false,
    comments: [
      { id: 22, user: "nadia.rpm", text: "Timeless. One of the most important albums ever made.", time: "1d ago" },
      { id: 23, user: "max.plays", text: "The string arrangements on this album are absolutely gorgeous", time: "1d ago" },
      { id: 24, user: "zara.grooves", text: "Mercy Mercy Me still gives me chills every time", time: "1d ago" },
    ],
    bookmarked: false,
    timeAgo: "1d ago",
    createdAt: now - 115200000,
    accent: "#ec4899",
  },
  {
    id: 2011,
    user: "bjorn.grooves",
    caption: "Finally got my hands on a clean copy. The riffs on this record literally invented a genre. Played it three times back to back and my neighbors are not happy.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Master of Puppets", artist: "Metallica" },
    likes: 39,
    liked: false,
    comments: [
      { id: 25, user: "riku.records", text: "GOAT metal album. Orion alone makes it a masterpiece.", time: "2d ago" },
      { id: 26, user: "thomas.wax", text: "Even as a rock guy I can appreciate the musicianship here", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 172800000,
    accent: "#10b981",
  },
  {
    id: 2012,
    user: "beau.plays",
    caption: "Every Friday night needs a proper warm-up. This is mine. French house forever. The sample work on this album changed dance music.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Homework", artist: "Daft Punk" },
    likes: 45,
    liked: false,
    comments: [
      { id: 27, user: "juniper.sounds", text: "Da Funk into Rollin & Scratchin is the best 1-2 punch in electronic music", time: "2d ago" },
      { id: 28, user: "beau.plays", text: "Absolutely! The energy never drops", time: "2d ago" },
    ],
    bookmarked: false,
    timeAgo: "2d ago",
    createdAt: now - 180000000,
    accent: "#f59e0b",
  },
  {
    id: 2013,
    user: "milo.vinyl",
    caption: "Rainy afternoon, hot tea, and Nick Drake. This is what vinyl was made for. The intimacy of Pink Moon on a good system is unmatched.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Pink Moon", artist: "Nick Drake" },
    likes: 28,
    liked: false,
    comments: [
      { id: 29, user: "cleo.spins", text: "Nick Drake's voice in a quiet room is pure therapy", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 259200000,
    accent: "#84cc16",
  },
  {
    id: 2014,
    user: "dax.wax",
    caption: "Dollar bin treasure! Found this absolute gem for $0.50. The cover is beat up but the record plays VG+. This is why I dig. You never know what's hiding in those cheap bins.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "There's a Riot Goin' On", artist: "Sly & The Family Stone" },
    likes: 36,
    liked: false,
    comments: [
      { id: 30, user: "max.plays", text: "Dollar bin king strikes again! Great find.", time: "3d ago" },
      { id: 31, user: "lena.records", text: "Family Affair is such a vibe. Incredible album.", time: "3d ago" },
    ],
    bookmarked: false,
    timeAgo: "3d ago",
    createdAt: now - 270000000,
    accent: "#06b6d4",
  },
  {
    id: 2015,
    user: "zara.grooves",
    caption: "Turned my living room into Kingston for the evening. Burning incense, this on the turntable, and nowhere to be. Pure bliss.",
    mediaUrl: null,
    mediaType: "image",
    taggedRecord: { album: "Catch a Fire", artist: "Bob Marley & The Wailers" },
    likes: 31,
    liked: false,
    comments: [
      { id: 32, user: "felix.rpm", text: "Island Records pressings of the Wailers stuff sound so good!", time: "4d ago" },
    ],
    bookmarked: false,
    timeAgo: "4d ago",
    createdAt: now - 345600000,
    accent: "#10b981",
  },
];

export default INITIAL_POSTS;
